<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FlCountry;

class FlCountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = array (
  0 => 
  array (
    'code' => 'andorra',
    'name' => 'Andorra',
    'iso_code' => 'AD',
    'shop_url' => 'https://andorra.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  1 => 
  array (
    'code' => 'argentina',
    'name' => 'Argentina',
    'iso_code' => 'AR',
    'shop_url' => 'https://argentina.4life.com/corp/shop/all',
    'currency_code' => 'ARS',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  2 => 
  array (
    'code' => 'austria',
    'name' => 'Austria',
    'iso_code' => 'AT',
    'shop_url' => 'https://austria.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  3 => 
  array (
    'code' => 'bosniaandherzegovina',
    'name' => 'Bosnia and Herzegovina',
    'iso_code' => 'BA',
    'shop_url' => 'https://bosniaandherzegovina.4life.com/corp/shop/all',
    'currency_code' => 'BAM',
    'currency_symbol' => 'KM',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  4 => 
  array (
    'code' => 'belgium',
    'name' => 'Belgium',
    'iso_code' => 'BE',
    'shop_url' => 'https://belgium.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  5 => 
  array (
    'code' => 'bulgaria',
    'name' => 'Bulgaria',
    'iso_code' => 'BG',
    'shop_url' => 'https://bulgaria.4life.com/corp/shop/all',
    'currency_code' => 'BGN',
    'currency_symbol' => 'лв',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  6 => 
  array (
    'code' => 'bolivia',
    'name' => 'Bolivia',
    'iso_code' => 'BO',
    'shop_url' => 'https://bolivia.4life.com/corp/shop/all',
    'currency_code' => 'BOB',
    'currency_symbol' => 'Bs',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  7 => 
  array (
    'code' => 'belarus',
    'name' => 'Belarus',
    'iso_code' => 'BY',
    'shop_url' => 'https://belarus.4life.com/corp/shop/all',
    'currency_code' => 'BYN',
    'currency_symbol' => 'Br',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  8 => 
  array (
    'code' => 'switzerland',
    'name' => 'Switzerland',
    'iso_code' => 'CH',
    'shop_url' => 'https://switzerland.4life.com/corp/shop/all',
    'currency_code' => 'CHF',
    'currency_symbol' => 'CHF',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  9 => 
  array (
    'code' => 'chile',
    'name' => 'Chile',
    'iso_code' => 'CL',
    'shop_url' => 'https://chile.4life.com/corp/shop/all',
    'currency_code' => 'CLP',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  10 => 
  array (
    'code' => 'colombia',
    'name' => 'Colombia',
    'iso_code' => 'CO',
    'shop_url' => 'https://colombia.4life.com/corp/shop/all',
    'currency_code' => 'COP',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  11 => 
  array (
    'code' => 'costarica',
    'name' => 'Costarica',
    'iso_code' => 'CR',
    'shop_url' => 'https://costarica.4life.com/corp/shop/all',
    'currency_code' => 'CRC',
    'currency_symbol' => '₡',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  12 => 
  array (
    'code' => 'cyprus',
    'name' => 'Cyprus',
    'iso_code' => 'CY',
    'shop_url' => 'https://cyprus.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  13 => 
  array (
    'code' => 'czechrepublic',
    'name' => 'Czech Republic',
    'iso_code' => 'CZ',
    'shop_url' => 'https://czechrepublic.4life.com/corp/shop/all',
    'currency_code' => 'CZK',
    'currency_symbol' => 'Kč',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  14 => 
  array (
    'code' => 'germany',
    'name' => 'Germany',
    'iso_code' => 'DE',
    'shop_url' => 'https://germany.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  15 => 
  array (
    'code' => 'denmark',
    'name' => 'Denmark',
    'iso_code' => 'DK',
    'shop_url' => 'https://denmark.4life.com/corp/shop/all',
    'currency_code' => 'DKK',
    'currency_symbol' => 'kr',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  16 => 
  array (
    'code' => 'dominicanrepublic',
    'name' => 'Dominican Republic',
    'iso_code' => 'DO',
    'shop_url' => 'https://dominicanrepublic.4life.com/corp/shop/all',
    'currency_code' => 'DOP',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  17 => 
  array (
    'code' => 'ecuador',
    'name' => 'Ecuador',
    'iso_code' => 'EC',
    'shop_url' => 'https://ecuador.4life.com/corp/shop/all',
    'currency_code' => 'USD',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  18 => 
  array (
    'code' => 'estonia',
    'name' => 'Estonia',
    'iso_code' => 'EE',
    'shop_url' => 'https://estonia.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  19 => 
  array (
    'code' => 'spain',
    'name' => 'Spain',
    'iso_code' => 'ES',
    'shop_url' => 'https://spain.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  20 => 
  array (
    'code' => 'finland',
    'name' => 'Finland',
    'iso_code' => 'FI',
    'shop_url' => 'https://finland.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  21 => 
  array (
    'code' => 'france',
    'name' => 'France',
    'iso_code' => 'FR',
    'shop_url' => 'https://france.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  22 => 
  array (
    'code' => 'unitedkingdom',
    'name' => 'United Kingdom',
    'iso_code' => 'GB',
    'shop_url' => 'https://unitedkingdom.4life.com/corp/shop/all',
    'currency_code' => 'GBP',
    'currency_symbol' => '£',
    'locale' => 'en_GB',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  23 => 
  array (
    'code' => 'equatorialguinea',
    'name' => 'Equatorial Guinea',
    'iso_code' => 'GQ',
    'shop_url' => 'https://equatorialguinea.4life.com/corp/shop/all',
    'currency_code' => 'XAF',
    'currency_symbol' => 'FCFA',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  24 => 
  array (
    'code' => 'greece',
    'name' => 'Greece',
    'iso_code' => 'GR',
    'shop_url' => 'https://greece.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  25 => 
  array (
    'code' => 'guatemala',
    'name' => 'Guatemala',
    'iso_code' => 'GT',
    'shop_url' => 'https://guatemala.4life.com/corp/shop/all',
    'currency_code' => 'GTQ',
    'currency_symbol' => 'Q',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  26 => 
  array (
    'code' => 'honduras',
    'name' => 'Honduras',
    'iso_code' => 'HN',
    'shop_url' => 'https://honduras.4life.com/corp/shop/all',
    'currency_code' => 'HNL',
    'currency_symbol' => 'L',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  27 => 
  array (
    'code' => 'croatia',
    'name' => 'Croatia',
    'iso_code' => 'HR',
    'shop_url' => 'https://croatia.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  28 => 
  array (
    'code' => 'hungary',
    'name' => 'Hungary',
    'iso_code' => 'HU',
    'shop_url' => 'https://hungary.4life.com/corp/shop/all',
    'currency_code' => 'HUF',
    'currency_symbol' => 'Ft',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  29 => 
  array (
    'code' => 'ireland',
    'name' => 'Ireland',
    'iso_code' => 'IE',
    'shop_url' => 'https://ireland.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'en_GB',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  30 => 
  array (
    'code' => 'italy',
    'name' => 'Italy',
    'iso_code' => 'IT',
    'shop_url' => 'https://italy.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  31 => 
  array (
    'code' => 'lithuania',
    'name' => 'Lithuania',
    'iso_code' => 'LT',
    'shop_url' => 'https://lithuania.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  32 => 
  array (
    'code' => 'luxembourg',
    'name' => 'Luxembourg',
    'iso_code' => 'LU',
    'shop_url' => 'https://luxembourg.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  33 => 
  array (
    'code' => 'latvia',
    'name' => 'Latvia',
    'iso_code' => 'LV',
    'shop_url' => 'https://latvia.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  34 => 
  array (
    'code' => 'macedonia',
    'name' => 'North Macedonia',
    'iso_code' => 'MK',
    'shop_url' => 'https://macedonia.4life.com/corp/shop/all',
    'currency_code' => 'MKD',
    'currency_symbol' => 'ден',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  35 => 
  array (
    'code' => 'malta',
    'name' => 'Malta',
    'iso_code' => 'MT',
    'shop_url' => 'https://malta.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  36 => 
  array (
    'code' => 'mexico',
    'name' => 'Mexico',
    'iso_code' => 'MX',
    'shop_url' => 'https://mexico.4life.com/corp/shop/all',
    'currency_code' => 'MXN',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  37 => 
  array (
    'code' => 'nicaragua',
    'name' => 'Nicaragua',
    'iso_code' => 'NI',
    'shop_url' => 'https://nicaragua.4life.com/corp/shop/all',
    'currency_code' => 'NIO',
    'currency_symbol' => 'C$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  38 => 
  array (
    'code' => 'netherlands',
    'name' => 'Netherlands',
    'iso_code' => 'NL',
    'shop_url' => 'https://netherlands.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  39 => 
  array (
    'code' => 'norway',
    'name' => 'Norway',
    'iso_code' => 'NO',
    'shop_url' => 'https://norway.4life.com/corp/shop/all',
    'currency_code' => 'NOK',
    'currency_symbol' => 'kr',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  40 => 
  array (
    'code' => 'panama',
    'name' => 'Panama',
    'iso_code' => 'PA',
    'shop_url' => 'https://panama.4life.com/corp/shop/all',
    'currency_code' => 'USD',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  41 => 
  array (
    'code' => 'peru',
    'name' => 'Peru',
    'iso_code' => 'PE',
    'shop_url' => 'https://peru.4life.com/corp/shop/all',
    'currency_code' => 'PEN',
    'currency_symbol' => 'S/',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  42 => 
  array (
    'code' => 'poland',
    'name' => 'Poland',
    'iso_code' => 'PL',
    'shop_url' => 'https://poland.4life.com/corp/shop/all',
    'currency_code' => 'PLN',
    'currency_symbol' => 'zł',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  43 => 
  array (
    'code' => 'portugal',
    'name' => 'Portugal',
    'iso_code' => 'PT',
    'shop_url' => 'https://portugal.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  44 => 
  array (
    'code' => 'paraguay',
    'name' => 'Paraguay',
    'iso_code' => 'PY',
    'shop_url' => 'https://paraguay.4life.com/corp/shop/all',
    'currency_code' => 'PYG',
    'currency_symbol' => '₲',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  45 => 
  array (
    'code' => 'romania',
    'name' => 'Romania',
    'iso_code' => 'RO',
    'shop_url' => 'https://romania.4life.com/corp/shop/all',
    'currency_code' => 'RON',
    'currency_symbol' => 'lei',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  46 => 
  array (
    'code' => 'serbia',
    'name' => 'Serbia',
    'iso_code' => 'RS',
    'shop_url' => 'https://serbia.4life.com/corp/shop/all',
    'currency_code' => 'RSD',
    'currency_symbol' => 'дин',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  47 => 
  array (
    'code' => 'russia',
    'name' => 'Russia',
    'iso_code' => 'RU',
    'shop_url' => 'https://russia.4life.com/corp/shop/all',
    'currency_code' => 'RUB',
    'currency_symbol' => '₽',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  48 => 
  array (
    'code' => 'sweden',
    'name' => 'Sweden',
    'iso_code' => 'SE',
    'shop_url' => 'https://sweden.4life.com/corp/shop/all',
    'currency_code' => 'SEK',
    'currency_symbol' => 'kr',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  49 => 
  array (
    'code' => 'slovenia',
    'name' => 'Slovenia',
    'iso_code' => 'SI',
    'shop_url' => 'https://slovenia.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  50 => 
  array (
    'code' => 'slovakia',
    'name' => 'Slovakia',
    'iso_code' => 'SK',
    'shop_url' => 'https://slovakia.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  51 => 
  array (
    'code' => 'sanmarino',
    'name' => 'Sanmarino',
    'iso_code' => 'SM',
    'shop_url' => 'https://sanmarino.4life.com/corp/shop/all',
    'currency_code' => 'EUR',
    'currency_symbol' => '€',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  52 => 
  array (
    'code' => 'elsalvador',
    'name' => 'Elsalvador',
    'iso_code' => 'SV',
    'shop_url' => 'https://elsalvador.4life.com/corp/shop/all',
    'currency_code' => 'USD',
    'currency_symbol' => '$',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  53 => 
  array (
    'code' => 'turkey',
    'name' => 'Turkey',
    'iso_code' => 'TR',
    'shop_url' => 'https://turkey.4life.com/corp/shop/all',
    'currency_code' => 'TRY',
    'currency_symbol' => '₺',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  54 => 
  array (
    'code' => 'ukraine',
    'name' => 'Ukraine',
    'iso_code' => 'UA',
    'shop_url' => 'https://ukraine.4life.com/corp/shop/all',
    'currency_code' => 'UAH',
    'currency_symbol' => '₴',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  55 => 
  array (
    'code' => 'usspanish',
    'name' => 'United States (Spanish Store)',
    'iso_code' => 'US',
    'shop_url' => 'https://usspanish.4life.com/corp/shop/all',
    'currency_code' => 'USD',
    'currency_symbol' => '$',
    'locale' => 'es_US',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
  56 => 
  array (
    'code' => 'venezuela',
    'name' => 'Venezuela',
    'iso_code' => 'VE',
    'shop_url' => 'https://venezuela.4life.com/corp/shop/all',
    'currency_code' => 'VES',
    'currency_symbol' => 'Bs.',
    'locale' => 'es_ES',
    'is_active' => true,
    'scrape_method' => 'puppeteer',
    'scrape_status' => 'never',
    'scrape_days' => '[1,21]',
  ),
);

        foreach ($countries as $c) {
            FlCountry::updateOrCreate(
                ['code' => $c['code']],
                $c
            );
        }
    }
}
