<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FlProductReference;

class FlProductsReferenceSeeder extends Seeder
{
    public function run(): void
    {
        $products = [

            [
                'name' => '4Life Transfer Factor Plus Tri-Factor Formula',
                'slug' => 'transfer-factor-plus-tri-factor',
                'category' => 'Immune System',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "Zinc", "amount": null, "unit": "mg", "details": "as zinc mono-L-methionine sulfate"}, {"name": "4Life Tri-Factor Formula (UltraFactor, OvoFactor, NanoFactor)", "amount": "300", "unit": "mg", "details": "from cow colostrum and egg yolk"}, {"name": "Proprietary Polysaccharide Complex (IP-6, β-Sitosterol)", "amount": null, "unit": "mg", "details": null}, {"name": "Cordyceps sinensis mycelium extract", "amount": null, "unit": "mg", "details": "mushroom"}, {"name": "Bakers yeast extract", "amount": null, "unit": "mg", "details": null}, {"name": "Agaricus blazeii fruiting body extract", "amount": null, "unit": "mg", "details": "mushroom"}, {"name": "Aloe vera leaf gel extract", "amount": null, "unit": "mg", "details": null}, {"name": "Oat seed extract", "amount": null, "unit": "mg", "details": null}, {"name": "Olive leaf extract", "amount": null, "unit": "mg", "details": null}, {"name": "Maitake fruiting body extract", "amount": null, "unit": "mg", "details": "mushroom"}, {"name": "Shiitake fruiting body extract", "amount": null, "unit": "mg", "details": "mushroom"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor 300mg + zinc + superhongos (Cordyceps, Agaricus, Maitake, Shiitake) + aloe vera + avena + olivo. NSF certified.',
                'mechanism' => 'Respalda 4 tipos de células inmunológicas: NK, T, B y macrófagos. El zinc contribuye al sistema inmunitario. Clínicamente comprobado: activa sistema inmunológico en 2 horas.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día con 240 ml de agua.',
                'benefits' => 'Soporte inmunitario superior con respaldo para 4 tipos de células inmunológicas.',
                'warnings' => 'Contiene derivados de leche (calostro), huevo (yema) y soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Tri-Factor Formula',
                'slug' => 'transfer-factor-tri-factor',
                'category' => 'Immune System',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula (UltraFactor, OvoFactor, NanoFactor)", "amount": "600", "unit": "mg", "details": "from cow colostrum and egg yolk"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor Formula 600mg (UltraFactor + OvoFactor + NanoFactor).',
                'mechanism' => 'Respalda 3 tipos de células: NK, T y B. Clínicamente comprobado: activa sistema inmunológico en 2 horas. Protegido por patente.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día con 240 ml de agua.',
                'benefits' => 'Soporte inmunitario fundamental basado en péptidos bioactivos.',
                'warnings' => 'Contiene derivados de leche (calostro) y huevo (yema).',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Classic',
                'slug' => 'transfer-factor-classic',
                'category' => 'Immune System',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "UltraFactor (from cow colostrum)", "amount": "600", "unit": "mg", "details": "colostrum only, no egg"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'UltraFactor 600mg de calostro bovino. Fórmula clásica original.',
                'mechanism' => 'Respalda células NK. Solo calostro bovino (sin yema de huevo). Producto introductorio.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día con 240 ml de agua.',
                'benefits' => 'Producto introductorio para apoyo inmune fundamental.',
                'warnings' => 'Contiene derivados de leche (calostro).',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Chewable Tri-Factor Formula',
                'slug' => 'transfer-factor-chewable',
                'category' => 'Immune System',
                'format' => 'chewables',
                'serving_size' => '3 tablets',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula (UltraFactor, OvoFactor, NanoFactor)", "amount": "600", "unit": "mg", "details": "citrus cream flavor"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor 600mg en masticable sabor cítrico cremoso.',
                'mechanism' => 'Misma fórmula Tri-Factor en masticable. Activa sistema inmunológico en 2 horas.',
                'dosage_instructions' => 'Tomar 3 comprimidos masticables al día.',
                'benefits' => 'Opción masticable para quienes prefieren no tragar cápsulas.',
                'warnings' => 'Contiene derivados de leche, huevo, azúcares y edulcorante.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Immune Spray',
                'slug' => 'transfer-factor-immune-spray',
                'category' => 'Immune System',
                'format' => 'spray',
                'serving_size' => '5 sprays',
                'servings_per_container' => 60,
                'ingredients' => json_encode(json_decode('[{"name": "Zinc", "amount": null, "unit": "mg", "details": null}, {"name": "4Life Transfer Factor Blend (UltraFactor, NanoFactor)", "amount": null, "unit": "mg", "details": null}, {"name": "Proprietary Blend (colloidal silver, marshmallow, aloe, lactoferrin)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor Blend + zinc + plata coloidal + malvavisco + aloe + lactoferrina. Sabor menta o naranja.',
                'mechanism' => 'Spray con zinc y Transfer Factor para respaldo inmune rápido de absorción sublingual.',
                'dosage_instructions' => 'Rociar 5 veces en la boca al día.',
                'benefits' => 'Formato spray portátil para respaldo inmune rápido.',
                'warnings' => 'Contiene derivados de leche (calostro y lactoferrina).',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor RenewAll',
                'slug' => 'transfer-factor-renewall',
                'category' => 'Immune System',
                'format' => 'gel',
                'serving_size' => 'apply as needed',
                'servings_per_container' => null,
                'ingredients' => json_encode(json_decode('[{"name": "UltraFactor", "amount": null, "unit": null, "details": null}, {"name": "Aloe vera leaf juice", "amount": null, "unit": null, "details": null}, {"name": "Lavender, chamomile, rosemary, eucalyptus", "amount": null, "unit": null, "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Gel tópico con UltraFactor + aloe vera + lavanda + manzanilla + romero + eucalipto. Sin parabenos.',
                'mechanism' => 'Gel para la piel con Transfer Factor y emolientes botánicos. Contraresta resequedad.',
                'dosage_instructions' => 'Aplicar sobre la piel según sea necesario.',
                'benefits' => 'Gel tópico sin parabenos para piel sensible.',
                'warnings' => 'Contiene derivados de leche. Solo uso externo. Libre de crueldad animal.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Immune Boost',
                'slug' => 'transfer-factor-immune-boost',
                'category' => 'Immune System',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 5,
                'ingredients' => json_encode(json_decode('[{"name": "Vitamin C", "amount": "1000", "unit": "mg", "details": "multiple forms"}, {"name": "4Life Tri-Factor Formula", "amount": "1000", "unit": "mg", "details": "highest TF of any 4Life product"}, {"name": "Electrolytes (Na, Ca, Mg, Zn)", "amount": null, "unit": "mg", "details": null}, {"name": "Vitamins B6, D, K2, B2", "amount": null, "unit": null, "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => '1000mg TF + 1000mg vitamina C + zinc + vitaminas D, K2, B6, B2 + electrolitos. Sabor mandarina.',
                'mechanism' => 'Mayor cantidad de Transfer Factor de cualquier producto 4Life (1000mg). Vitamina C + electrolitos. Acción rápida.',
                'dosage_instructions' => 'Mezclar 1 sobre con agua cuando necesite respaldo inmune rápido.',
                'benefits' => 'Respaldo inmune de acción rápida con la mayor dosis de Transfer Factor.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life TF-Boost',
                'slug' => 'tf-boost-sachets',
                'category' => 'Immune System',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 5,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": "1000", "unit": "mg", "details": null}, {"name": "Vitamin C", "amount": null, "unit": "mg", "details": null}, {"name": "Vitamin D", "amount": null, "unit": "µg", "details": null}, {"name": "Vitamin B6", "amount": null, "unit": "mg", "details": null}, {"name": "Vitamin B2", "amount": null, "unit": "mg", "details": null}, {"name": "Zinc", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor 1000mg + vitaminas C, D, B6, B2 + zinc. Sabor naranja con estevia. Versión europea.',
                'mechanism' => 'Vitaminas B6, C, D y zinc contribuyen al sistema inmunitario. Vitaminas C, B2 y zinc protegen células del daño oxidativo.',
                'dosage_instructions' => 'Mezclar 1 sobre con 180 ml de agua. Una vez al día.',
                'benefits' => 'Apoyo inmune potente + antioxidante + energía. Formato europeo.',
                'warnings' => 'Contiene derivados de leche y huevo. No uso prolongado sin consejo especialista.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Cardio',
                'slug' => 'transfer-factor-cardio',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Transfer Factor (colostrum filtrate, OvoFactor, NanoFactor)", "amount": null, "unit": "mg", "details": null}, {"name": "Coenzyme Q10", "amount": null, "unit": "mg", "details": null}, {"name": "Garlic bulb extract", "amount": null, "unit": "mg", "details": null}, {"name": "Red rice yeast extract", "amount": null, "unit": "mg", "details": "contains monacolin"}, {"name": "Resveratrol (Polygonum cuspidatum)", "amount": null, "unit": "mg", "details": null}, {"name": "Ginkgo biloba", "amount": null, "unit": "mg", "details": null}, {"name": "Magnesium", "amount": null, "unit": "mg", "details": null}, {"name": "Selenium", "amount": null, "unit": "µg", "details": null}, {"name": "Vitamins B6, B12, folic acid", "amount": null, "unit": null, "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + CoQ10, ajo, arroz de levadura roja, resveratrol, ginkgo, magnesio, selenio, vitaminas B6/B9/B12.',
                'mechanism' => 'Protección cardíaca: reduce estrés oxidativo y modula inflamación (estudio preclínico). B6/B9/B12 metabolizan homocisteína.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte cardiovascular: corazón, circulación y función vascular.',
                'warnings' => 'No más de 3mg monacolina/día. No usar con estatinas. Consultar con anticoagulantes.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor ReCall',
                'slug' => 'transfer-factor-recall',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor Blend", "amount": null, "unit": "mg", "details": null}, {"name": "Huperzia serrata extract", "amount": null, "unit": "mg", "details": null}, {"name": "Bacopa monnieri extract", "amount": null, "unit": "mg", "details": null}, {"name": "Ginkgo biloba extract", "amount": null, "unit": "mg", "details": null}, {"name": "Phosphatidylserine", "amount": null, "unit": "mg", "details": null}, {"name": "Vinpocetine", "amount": null, "unit": "mg", "details": null}, {"name": "L-glutamine", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + Huperzia serrata, Bacopa, Ginkgo, fosfatidilserina, vinpocetina, L-glutamina.',
                'mechanism' => 'Respaldo cerebral: Huperzia, Bacopa y Ginkgo promueven circulación cerebral, memoria y función cognitiva.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para memoria, concentración y función cognitiva.',
                'warnings' => 'Consultar con anticoagulantes. Contiene derivados de leche, huevo y soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor GluCoach',
                'slug' => 'transfer-factor-glucoach',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor", "amount": null, "unit": "mg", "details": null}, {"name": "Chromium", "amount": null, "unit": "µg", "details": "maintains normal blood glucose"}, {"name": "Ceylon cinnamon", "amount": null, "unit": "mg", "details": null}, {"name": "Nopal cactus", "amount": null, "unit": "mg", "details": null}, {"name": "Banaba", "amount": null, "unit": "mg", "details": null}, {"name": "Panax ginseng", "amount": null, "unit": "mg", "details": null}, {"name": "Pterocarpus marsupium", "amount": null, "unit": "mg", "details": null}, {"name": "Bitter melon", "amount": null, "unit": "mg", "details": null}, {"name": "Fenugreek", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + cromo + canela de Ceilán, nopal, banaba, ginseng, pterocarpus, melón amargo, fenogreco.',
                'mechanism' => 'Cromo contribuye a niveles normales de glucosa y metabolismo de macronutrientes. Respalda páncreas y sistema endocrino.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte del metabolismo de glucosa y sistema endocrino.',
                'warnings' => 'Consultar médico si usa medicación para glucosa. Contiene leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor AgePro',
                'slug' => 'transfer-factor-agepro',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Nicotinamide mononucleotide (NMN)", "amount": null, "unit": "mg", "details": "NAD+ precursor"}, {"name": "Apigenin", "amount": null, "unit": "mg", "details": null}, {"name": "Quercetin dihydrate", "amount": null, "unit": "mg", "details": null}, {"name": "White button mushroom extract", "amount": null, "unit": "mg", "details": null}, {"name": "Alpha-ketoglutaric acid", "amount": null, "unit": "mg", "details": null}, {"name": "Colostrum filtrate + NanoFactor + OvoFactor", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'NMN + apigenina + quercetina + champiñón + AKG + Transfer Factor.',
                'mechanism' => 'Incrementa NAD+ en sangre. Mejora duración de salud y esperanza de vida. Rejuvenece células inmunológicas envejecidas.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día con 240 ml de agua.',
                'benefits' => 'Soporte para longevidad, envejecimiento celular saludable y desempeño físico.',
                'warnings' => 'No apto para embarazadas, lactantes ni niños. Contiene leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Collagen',
                'slug' => 'transfer-factor-collagen',
                'category' => 'Targeted Transfer Factor',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "Vitamins A, C, E + Biotin", "amount": null, "unit": null, "details": null}, {"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Hydrolyzed fish collagen (type I)", "amount": null, "unit": "mg", "details": null}, {"name": "Chicken bone broth collagen (types I, II, III)", "amount": null, "unit": "mg", "details": null}, {"name": "Eggshell membrane collagen (types I, V, X)", "amount": null, "unit": "mg", "details": null}, {"name": "Age-Defying Plant Complex", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => '5 tipos colágeno (pescado, pollo, membrana huevo) + vitaminas A, C, E + biotina + Tri-Factor. Sabor fresa y mango.',
                'mechanism' => 'Vitamina C forma colágeno para piel. Biotina para cabello. Vitaminas A, C, E protegen del daño oxidativo.',
                'dosage_instructions' => 'Mezclar 1 sobre con 240 ml o más de bebida. Una vez al día.',
                'benefits' => 'Soporte para piel, cabello, uñas, articulaciones y músculos con 5 tipos de colágeno.',
                'warnings' => 'Contiene derivados de leche, huevo, pescado y trigo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Collagen Type I',
                'slug' => 'transfer-factor-collagen-type-i',
                'category' => 'Targeted Transfer Factor',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Hydrolyzed collagen type I", "amount": null, "unit": "mg", "details": "unflavored"}, {"name": "Vitamin C", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Colágeno tipo I sin sabor + vitamina C + Tri-Factor Formula.',
                'mechanism' => 'Respalda elasticidad, humectación, tono y reparación de la piel.',
                'dosage_instructions' => 'Mezclar 1 sobre con bebida preferida. Una vez al día.',
                'benefits' => 'Soporte para piel, uñas, cabello. Sin sabor para mezclar con cualquier bebida.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life NanoFactor Glutamine Prime',
                'slug' => 'nanofactor-glutamine-prime',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "L-glutamine", "amount": null, "unit": "mg", "details": null}, {"name": "L-arginine", "amount": null, "unit": "mg", "details": null}, {"name": "N-acetyl-L-cysteine", "amount": null, "unit": "mg", "details": "glutathione precursor"}, {"name": "Alpha lipoic acid", "amount": null, "unit": "mg", "details": null}, {"name": "L-alanyl-L-glutamine", "amount": null, "unit": "mg", "details": null}, {"name": "NanoFactor", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'L-glutamina + L-arginina + NAC + ácido alfa lipoico + NanoFactor.',
                'mechanism' => 'Aporta energía a células inmunológicas con glutamina. Proporciona componentes del glutatión antioxidante.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte energético para células inmunológicas y antioxidante (glutatión).',
                'warnings' => 'Contiene derivados de leche (calostro).',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Metabolite',
                'slug' => 'transfer-factor-metabolite',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor", "amount": null, "unit": "mg", "details": null}, {"name": "Thyroid support blend", "amount": null, "unit": "mg", "details": "iodine, selenium, guggul"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + mezcla de soporte tiroideo + antioxidantes.',
                'mechanism' => 'Respalda tiroides. Modera hormonas tiroideas. Reduce estrés oxidativo post-comidas.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para metabolismo tiroideo y control de peso.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor KBU',
                'slug' => 'transfer-factor-kbu',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor", "amount": null, "unit": "mg", "details": null}, {"name": "Cranberry", "amount": null, "unit": "mg", "details": null}, {"name": "Blueberry extract", "amount": null, "unit": "mg", "details": null}, {"name": "Dandelion leaf", "amount": null, "unit": "mg", "details": null}, {"name": "Juniper berry", "amount": null, "unit": "mg", "details": null}, {"name": "IP-6", "amount": null, "unit": "mg", "details": null}, {"name": "Chanca piedra", "amount": null, "unit": "mg", "details": null}, {"name": "Crataeva nurvala", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + arándanos, diente de león, enebro, IP-6, chanca piedra, Crataeva.',
                'mechanism' => 'Respaldo tracto urinario, riñones y vejiga. Arándanos y enebro para funcionamiento urinario. Filtración renal saludable.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para salud urinaria, renal y desintoxicación.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Lung',
                'slug' => 'transfer-factor-lung',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Vitamin C", "amount": null, "unit": "mg", "details": null}, {"name": "Thyme extract", "amount": null, "unit": "mg", "details": "respiratory"}, {"name": "NAC", "amount": null, "unit": "mg", "details": "bronchial"}, {"name": "Panax ginseng", "amount": null, "unit": "mg", "details": null}, {"name": "Vitamins A, E", "amount": null, "unit": null, "details": null}, {"name": "Broccoli seed extract", "amount": null, "unit": "mg", "details": null}, {"name": "Black cumin seed", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor + tomillo, NAC, vitaminas A/C/E, ginseng, brócoli, comino negro.',
                'mechanism' => 'Promueve función respiratoria. Respalda tejido pulmonar. Desintoxica de contaminación del aire.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día, una en cada comida.',
                'benefits' => 'Soporte integral del sistema respiratorio y pulmones.',
                'warnings' => 'No menores de 3 años. No con disfunción tiroidea. No embarazadas/lactantes.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Vista',
                'slug' => 'transfer-factor-vista',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '1 capsule',
                'servings_per_container' => 60,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Lutein", "amount": null, "unit": "mg", "details": "macula"}, {"name": "Zeaxanthin", "amount": null, "unit": "mg", "details": "macula"}, {"name": "Astaxanthin", "amount": null, "unit": "mg", "details": null}, {"name": "Vitamins A, C, E", "amount": null, "unit": null, "details": null}, {"name": "Zinc", "amount": null, "unit": "mg", "details": null}, {"name": "Bilberry extract", "amount": null, "unit": "mg", "details": null}, {"name": "Ginkgo biloba", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor + luteína, zeaxantina, astaxantina, vitaminas A/C/E, zinc, arándano, ginkgo.',
                'mechanism' => 'Vitamina A y zinc para visión normal. Luteína/zeaxantina reducen daño oxidativo del sol y luz azul en mácula.',
                'dosage_instructions' => 'Tomar 1 cápsula al día con 240 ml de líquido.',
                'benefits' => 'Soporte completo de salud ocular y agudeza visual.',
                'warnings' => 'Consultar con anticoagulantes. Contiene leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Belle Vie',
                'slug' => 'transfer-factor-belle-vie',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Antioxidant Blend (green tea, grapeseed)", "amount": null, "unit": "mg", "details": null}, {"name": "Phytoestrogen Blend (flaxseed, kudzu, red clover)", "amount": null, "unit": "mg", "details": null}, {"name": "Cruciferous Blend (broccoli, cabbage, kale, I3C, DIM, calcium d-glucarate)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor + antioxidantes + fitoestrógenos + crucíferas (I3C, DIM, D-glucarato de calcio).',
                'mechanism' => 'Respaldo salud reproductiva femenina y senos. Fitoestrógenos e indoles para sistema endocrino femenino.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para salud reproductiva femenina y equilibrio hormonal.',
                'warnings' => 'Contiene derivados de leche, huevo y soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor MalePro',
                'slug' => 'transfer-factor-malepro',
                'category' => 'Targeted Transfer Factor',
                'format' => 'softgels',
                'serving_size' => '3 softgels',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor", "amount": null, "unit": "mg", "details": null}, {"name": "Saw palmetto extract", "amount": null, "unit": "mg", "details": "prostate"}, {"name": "Lycopene", "amount": null, "unit": "mg", "details": null}, {"name": "Isoflavones (soy)", "amount": null, "unit": "mg", "details": null}, {"name": "Broccoli extract", "amount": null, "unit": "mg", "details": null}, {"name": "Pumpkin seed", "amount": null, "unit": "mg", "details": null}, {"name": "Zinc", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + palma enana, licopeno, isoflavonas, brócoli, semilla de calabaza, zinc.',
                'mechanism' => 'Respaldo salud prostática. Palma enana, licopeno e isoflavonas contribuyen a salud de la próstata.',
                'dosage_instructions' => 'Tomar 3 cápsulas blandas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para salud prostática y bienestar del hombre.',
                'warnings' => 'Contiene derivados de leche, huevo y soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Reflexion',
                'slug' => 'transfer-factor-reflexion',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Wild green oat (Avena sativa) extract", "amount": null, "unit": "mg", "details": null}, {"name": "L-theanine", "amount": null, "unit": "mg", "details": "relaxation without drowsiness"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor + avena verde silvestre + L-teanina.',
                'mechanism' => 'Mejora manejo del estrés ocasional. Promueve relajación, ánimo positivo y concentración.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para estrés, ánimo, concentración y relajación.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor SleepRite',
                'slug' => 'transfer-factor-sleeprite',
                'category' => 'Targeted Transfer Factor',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor", "amount": null, "unit": "mg", "details": null}, {"name": "Sleep support blend (melatonin, valerian, hops, passionflower, L-theanine)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + mezcla para dormir (melatonina, valeriana, lúpulo, pasiflora, L-teanina).',
                'mechanism' => 'Ayuda a conciliar el sueño rápidamente y mejora calidad del sueño. Investigado clínicamente.',
                'dosage_instructions' => 'Tomar 2 cápsulas antes de dormir.',
                'benefits' => 'Soporte para sueño, relajación y equilibrio mente-cuerpo.',
                'warnings' => 'Contiene leche y huevo. No conducir después de tomar.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor RioVida Stix Tri-Factor Formula',
                'slug' => 'riovida-stix',
                'category' => 'RioVida',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": "600", "unit": "mg", "details": null}, {"name": "RioVida Blend (açaí, blueberry, elderberry, grapeseed, pomegranate)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor 600mg + açaí, arándano, saúco, uva, granada. Sin artificiales. Desde 2 años.',
                'mechanism' => 'Antioxidantes de superfrutas + Transfer Factor para respaldo inmune.',
                'dosage_instructions' => 'Mezclar 1 sobre con 60-120 ml de agua. Una vez al día.',
                'benefits' => 'Soporte inmune + antioxidante portátil para toda la familia.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor RioVida Burst Tri-Factor Formula',
                'slug' => 'riovida-burst',
                'category' => 'RioVida',
                'format' => 'gel packs',
                'serving_size' => '1 gel pack',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": "600", "unit": "mg", "details": null}, {"name": "RioVida Juice Blend (apple, grape, blueberry, açaí, pomegranate, elderberry)", "amount": null, "unit": "ml", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor 600mg + zumos RioVida (manzana, uva, arándano, açaí, granada, saúco). Formato gel.',
                'mechanism' => 'Gel con jugos de superfrutas antioxidantes + Transfer Factor. No requiere mezcla ni refrigeración.',
                'dosage_instructions' => 'Tomar 1 paquete de gel al día.',
                'benefits' => 'Soporte inmune + antioxidante en gel portátil listo para consumir.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor RioVida Chews',
                'slug' => 'riovida-chews',
                'category' => 'RioVida',
                'format' => 'chewables',
                'serving_size' => '2 chews',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "Vitamin C", "amount": null, "unit": "mg", "details": null}, {"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "RioVida Juice Blend", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Vitamina C + Tri-Factor + zumos RioVida. Formato masticable.',
                'mechanism' => 'Vitamina C antioxidante + Transfer Factor + superfrutas en masticable.',
                'dosage_instructions' => 'Tomar 2 masticables al día.',
                'benefits' => 'Soporte inmune + antioxidante + vitamina C en masticable.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'RiteStart',
                'slug' => 'ritestart',
                'category' => 'RiteStart',
                'format' => 'capsules + softgels',
                'serving_size' => 'daily pack',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor Plus Tri-Factor Formula", "amount": "300", "unit": "mg", "details": null}, {"name": "Essential Fatty Acid Complex (omega-3/6)", "amount": null, "unit": "mg", "details": "fish oil, flaxseed, borage, safflower"}, {"name": "Full multivitamin/mineral complex", "amount": null, "unit": null, "details": "25+ vitamins and minerals"}, {"name": "OPC, Antioxidant, and Support Blends", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'TF Plus 300mg + multivitamínico completo + omega-3/6 + OPC + antioxidantes + soporte articular.',
                'mechanism' => 'Paquete nutricional completo: inmune (TF Plus), vitaminas/minerales, ácidos grasos, antioxidantes, articular.',
                'dosage_instructions' => 'Tomar 1 paquete diario con la comida principal.',
                'benefits' => 'Nutrición completa diaria con respaldo inmune, multivitamínico y omega.',
                'warnings' => 'Contiene leche, huevo, soja y pescado.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'RiteStart Kids and Teens',
                'slug' => 'ritestart-kids-teens',
                'category' => 'RiteStart',
                'format' => 'chewables',
                'serving_size' => '2-4 tablets by age',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": "300-600", "unit": "mg", "details": "depending on age"}, {"name": "22 vitamins and minerals", "amount": null, "unit": null, "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor 300-600mg + 22 vitaminas y minerales. Sabor cítrico/manzana agria. Para 2-18 años.',
                'mechanism' => 'Respaldo inmune + multivitamínico para cuerpos en crecimiento. Vitaminas B y colina para cerebro.',
                'dosage_instructions' => '2-8 años: 2 tabletas/día. 9-18 años: 4 tabletas/día.',
                'benefits' => 'Nutrición completa para niños y adolescentes con Transfer Factor.',
                'warnings' => 'Contiene leche y huevo. Solo para 2-18 años.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'NutraStart Blue Vanilla',
                'slug' => 'nutrastart-blue-vanilla',
                'category' => 'RiteStart',
                'format' => 'powder',
                'serving_size' => '1 scoop',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Whey protein + 20+ vitamins/minerals", "amount": null, "unit": null, "details": null}, {"name": "Fiber blend (corn, apple, oat)", "amount": null, "unit": "g", "details": null}, {"name": "Blue spirulina", "amount": null, "unit": "mg", "details": "natural color"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor + proteína de suero + 20+ vitaminas/minerales + fibras + spirulina azul.',
                'mechanism' => 'Batido nutricional con Transfer Factor. Buena fuente de fibra, respalda saciedad.',
                'dosage_instructions' => 'Mezclar 1 cucharada con 240 ml de agua o leche.',
                'benefits' => 'Batido nutricional completo con Transfer Factor para control de peso.',
                'warnings' => 'Contiene leche, huevo, trigo y soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Pre/o Biotics',
                'slug' => 'pre-o-biotics',
                'category' => 'Digest4Life',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor Tri-Factor Formula", "amount": null, "unit": "mg", "details": "acts as prebiotic"}, {"name": "Probiotic blend (5 strains)", "amount": null, "unit": "CFU", "details": "microsphere delivery"}, {"name": "Prebiotic fiber", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor (prebiótico) + 5 cepas probióticas + prebióticos. Microesferas. Sin refrigeración.',
                'mechanism' => 'Único prebiótico/probiótico con Transfer Factor. Microesferas aumentan microbiota hasta 1000x vs estándar.',
                'dosage_instructions' => 'Mezclar 1 sobre con líquido al día.',
                'benefits' => 'Soporte digestivo e inmune con probióticos de alta supervivencia.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Aloe Vera Stix',
                'slug' => 'aloe-vera-stix',
                'category' => 'Digest4Life',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "Aloe vera powder", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Aloe vera en polvo para salud digestiva.',
                'mechanism' => 'Alivia tracto gastrointestinal. Asiste recuperación de limpiezas intestinales.',
                'dosage_instructions' => 'Mezclar 1 sobre con líquido al día.',
                'benefits' => 'Soporte gastrointestinal y recuperación post-limpieza.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Digestive Enzymes',
                'slug' => 'digestive-enzymes',
                'category' => 'Digest4Life',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Full digestive enzyme complex", "amount": null, "unit": "mg", "details": "protease, amylase, lipase, cellulase, lactase"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Fórmula completa de enzimas digestivas.',
                'mechanism' => 'Respalda digestión saludable y reduce molestias intestinales.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día con las comidas.',
                'benefits' => 'Soporte para digestión completa.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Fibre System Plus',
                'slug' => 'fibre-system-plus',
                'category' => 'Digest4Life',
                'format' => 'sachets',
                'serving_size' => '1 packet',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "20+ herbal cleanse blend", "amount": null, "unit": "mg", "details": "cascara sagrada, frangula, prune, pineapple, papain, bromelain"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => '20+ ingredientes herbarios. Limpieza gastrointestinal de 10 días.',
                'mechanism' => 'Limpieza GI de 10 días con más de 20 ingredientes herbarios.',
                'dosage_instructions' => 'Seguir programa de 10 días según guía incluida.',
                'benefits' => 'Limpieza gastrointestinal completa.',
                'warnings' => 'Programa de 10 días. Consultar médico.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Super Detox',
                'slug' => 'super-detox',
                'category' => 'Digest4Life',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Milk thistle extract", "amount": null, "unit": "mg", "details": "liver"}, {"name": "Red clover", "amount": null, "unit": "mg", "details": null}, {"name": "Artichoke", "amount": null, "unit": "mg", "details": null}, {"name": "NAC", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Cardo lechoso + trébol rojo + alcachofa + NAC.',
                'mechanism' => 'Cardo lechoso respalda hígado. Trébol rojo y alcachofa para desintoxicación. NAC antioxidante.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte hepático y desintoxicación.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'PhytoLax',
                'slug' => 'phytolax',
                'category' => 'Digest4Life',
                'format' => 'capsules',
                'serving_size' => '1 capsule',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Cascara sagrada", "amount": null, "unit": "mg", "details": null}, {"name": "Ginger", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Cáscara sagrada + jengibre.',
                'mechanism' => 'Activa eliminación digestiva segura. Promueve regularidad.',
                'dosage_instructions' => 'Tomar 1 cápsula al día.',
                'benefits' => 'Soporte para regularidad intestinal.',
                'warnings' => 'No uso prolongado sin supervisión.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Tea4Life',
                'slug' => 'tea4life',
                'category' => 'Digest4Life',
                'format' => 'tea bags',
                'serving_size' => '1 tea bag',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Senna leaf + herbal blend", "amount": null, "unit": "mg", "details": "apple and cinnamon flavor"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Hoja de sena + hierbas. Sabor manzana y canela. Sin artificiales.',
                'mechanism' => 'Té natural con sena para limpieza y regularidad intestinal.',
                'dosage_instructions' => 'Preparar 1 bolsita con agua caliente.',
                'benefits' => 'Té natural para regularidad intestinal.',
                'warnings' => 'Contiene sena. No uso prolongado.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Pro-TF',
                'slug' => 'pro-tf-protein',
                'category' => '4LifeTransform',
                'format' => 'powder',
                'serving_size' => '2 scoops',
                'servings_per_container' => 23,
                'ingredients' => json_encode(json_decode('[{"name": "Hydrolyzed whey + egg white protein", "amount": "20", "unit": "g protein", "details": "extensively hydrolyzed, high-DH"}, {"name": "4Life Tri-Factor Formula", "amount": "600", "unit": "mg", "details": null}, {"name": "MCT oil powder", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => '20g proteína hidrolizada + 600mg Tri-Factor + MCT. 140 cal, sin gluten, <1g lactosa. Vainilla o chocolate.',
                'mechanism' => 'Proteína patentada: quema calorías/grasas, protege/genera masa muscular, aumenta metabolismo, suprime apetito.',
                'dosage_instructions' => 'Mezclar 2 cucharadas con agua o leche. 1-2 veces al día.',
                'benefits' => 'Proteína premium con Transfer Factor para transformación corporal.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4LifeTransform PreZoom',
                'slug' => 'transform-prezoom',
                'category' => '4LifeTransform',
                'format' => 'powder',
                'serving_size' => '1 scoop',
                'servings_per_container' => 20,
                'ingredients' => json_encode(json_decode('[{"name": "CarnoSyn beta-alanine", "amount": null, "unit": "mg", "details": "patented"}, {"name": "Creatine + BCAA 2:1:1", "amount": null, "unit": "mg", "details": null}, {"name": "L-citrulline + L-glutamine + L-tyrosine + L-theanine", "amount": null, "unit": "mg", "details": null}, {"name": "Green tea extract", "amount": null, "unit": "mg", "details": null}, {"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Beta-alanina + creatina + BCAA + aminoácidos + té verde + Tri-Factor. Sabor sandía.',
                'mechanism' => 'Pre-entreno: aumenta masa muscular, fuerza y resistencia. Mejora enfoque. Respalda inmune durante ejercicio intenso.',
                'dosage_instructions' => 'Mezclar 1 cucharada con agua 15-30 min antes del ejercicio.',
                'benefits' => 'Pre-entreno con Transfer Factor para rendimiento y enfoque.',
                'warnings' => 'Contiene leche y huevo. Puede causar hormigueo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Transfer Factor Renuvo',
                'slug' => 'transfer-factor-renuvo',
                'category' => '4LifeTransform',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Tri-Factor Formula", "amount": null, "unit": "mg", "details": null}, {"name": "Adaptogenics Blend (Rhaponticum, Schisandra, ashwagandha)", "amount": null, "unit": "mg", "details": null}, {"name": "ALCAR + green tea + turmeric + resveratrol + black pepper", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Tri-Factor + adaptógenos patentados (Rhaponticum, Schisandra, Ashwagandha) + ALCAR + cúrcuma + resveratrol.',
                'mechanism' => 'Adaptógeno patentado: recuperación total, agudeza mental, energía, vitalidad sexual.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día con 240 ml de líquido.',
                'benefits' => 'Soporte para envejecimiento saludable, recuperación, energía y vitalidad.',
                'warnings' => 'Contiene derivados de leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4LifeTransform Burn',
                'slug' => 'transform-burn',
                'category' => '4LifeTransform',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 20,
                'ingredients' => json_encode(json_decode('[{"name": "Bitter orange + citrus extract", "amount": null, "unit": "mg", "details": "thermogenic"}, {"name": "Coleus forskohlii", "amount": null, "unit": "mg", "details": null}, {"name": "African mango seed extract", "amount": null, "unit": "mg", "details": null}, {"name": "Dihydrocapsiate", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Naranja amarga + Coleus forskohlii + mango africano + dihidrocapsiato.',
                'mechanism' => 'Mezcla termogénica: impulsa quema de grasa, reduce apetito, respaldo energético.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día.',
                'benefits' => 'Soporte para control de peso y quema de grasa.',
                'warnings' => 'Usar con dieta sana y ejercicio.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'ShapeRite',
                'slug' => 'shaperite',
                'category' => '4LifeTransform',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Chitosan (shellfish)", "amount": null, "unit": "mg", "details": "fat binder"}, {"name": "White kidney bean extract", "amount": null, "unit": "mg", "details": "starch blocker"}, {"name": "Hydrolyzed yeast extract", "amount": null, "unit": "mg", "details": null}, {"name": "Dragon fruit extract", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Chitosán + frijol blanco + levadura + fruta de dragón.',
                'mechanism' => 'Comprime grasas, bloquea almidones y azúcares. Equilibra hormonas de saciedad.',
                'dosage_instructions' => 'Tomar 3 cápsulas antes de las comidas.',
                'benefits' => 'Soporte para control de peso y metabolismo de grasas.',
                'warnings' => 'Contiene mariscos (chitosán).',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4LifeTransform Woman',
                'slug' => 'transform-woman',
                'category' => '4LifeTransform',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "L-citrulline", "amount": null, "unit": "mg", "details": "nitric oxide"}, {"name": "Evening primrose extract", "amount": null, "unit": "mg", "details": null}, {"name": "Velvet bean (Mucuna pruriens) extract", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'L-citrulina + onagra + Mucuna pruriens.',
                'mechanism' => 'Respalda envejecimiento celular, piel saludable y producción de óxido nítrico.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día.',
                'benefits' => 'Soporte para vitalidad femenina, piel y envejecimiento celular.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4LifeTransform Man',
                'slug' => 'transform-man',
                'category' => '4LifeTransform',
                'format' => 'capsules',
                'serving_size' => '4 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "L-citrulline", "amount": null, "unit": "mg", "details": null}, {"name": "Citrus peel extract", "amount": null, "unit": "mg", "details": null}, {"name": "Korean ginseng root extract", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'L-citrulina + cáscara de cítrico + ginseng coreano.',
                'mechanism' => 'Respalda envejecimiento celular, masa muscular magra, fuerza y salud del hombre.',
                'dosage_instructions' => 'Tomar 4 cápsulas al día.',
                'benefits' => 'Soporte para vitalidad masculina, masa muscular y salud ósea.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4LifeTransform Protein Bar',
                'slug' => 'transform-protein-bar',
                'category' => '4LifeTransform',
                'format' => 'bars',
                'serving_size' => '1 bar',
                'servings_per_container' => 10,
                'ingredients' => json_encode(json_decode('[{"name": "Protein Blend (soy, collagen, whey, milk, Transfer Factor)", "amount": null, "unit": "g", "details": "chocolate peanut butter"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Proteína (soja, colágeno, suero, leche, TF) + chocolate + crema de maní. 190 cal. Para +4 años.',
                'mechanism' => 'Alto contenido proteínico con Transfer Factor. 190 calorías.',
                'dosage_instructions' => 'Consumir 1 barra como snack proteínico.',
                'benefits' => 'Snack proteínico con Transfer Factor.',
                'warnings' => 'Contiene leche, huevo, soja, maní.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Energy Go Stix',
                'slug' => 'energy-go-stix',
                'category' => 'Energy',
                'format' => 'sachets',
                'serving_size' => '1 sachet',
                'servings_per_container' => 15,
                'ingredients' => json_encode(json_decode('[{"name": "4Life Transfer Factor Blend", "amount": null, "unit": "mg", "details": null}, {"name": "Amino Acid Blend (glutamine, arginine, taurine, creatine, carnitine, ornithine, AKG)", "amount": null, "unit": "mg", "details": null}, {"name": "3 types of ginseng (eleuthero, Korean, American)", "amount": null, "unit": "mg", "details": null}, {"name": "Herbal Energy Blend (green tea, yerba mate, guarana, maca, Rhodiola)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Transfer Factor + aminoácidos + 3 ginsengs + té verde + yerba mate + guaraná + maca + Rhodiola. 5 sabores.',
                'mechanism' => 'Mezcla sinérgica de aminoácidos, yerba mate, té verde y 3 ginsengs para energía. TF para inmune.',
                'dosage_instructions' => 'Mezclar 1 sobre con agua. Hasta 2 al día.',
                'benefits' => 'Energía + respaldo inmune portátil. 5 sabores.',
                'warnings' => 'Contiene cafeína natural. Contiene leche y huevo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Zinc Factor',
                'slug' => 'zinc-factor',
                'category' => '4LifeElements',
                'format' => 'liquid',
                'serving_size' => '1 tablespoon',
                'servings_per_container' => 40,
                'ingredients' => json_encode(json_decode('[{"name": "Zinc (ionic)", "amount": "6", "unit": "ppm", "details": null}, {"name": "Silver (ionic)", "amount": "12", "unit": "ppm", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Zinc iónico (6 ppm) + plata iónica (12 ppm). Proceso electroquímico exclusivo.',
                'mechanism' => 'Zinc impulsa células T. Combina zinc y plata iónica para respaldo inmune.',
                'dosage_instructions' => 'Tomar 1 cucharada sopera al día.',
                'benefits' => 'Solución mineral iónica para respaldo inmune.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Gold Factor',
                'slug' => 'gold-factor',
                'category' => '4LifeElements',
                'format' => 'liquid',
                'serving_size' => '1 tablespoon',
                'servings_per_container' => 40,
                'ingredients' => json_encode(json_decode('[{"name": "Gold (nanoparticles)", "amount": "6", "unit": "ppm", "details": "purer than 24K gold"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Partículas de oro (6 ppm). Color rosa por refracción. Más puro que oro 24K.',
                'mechanism' => 'Miles de millones de partículas de oro activan células. Respaldo articular (estudio clínico).',
                'dosage_instructions' => 'Tomar 1 cucharada sopera al día.',
                'benefits' => 'Respaldo celular, longevidad, cerebro y articulaciones.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Essential Fatty Acid Complex',
                'slug' => 'essential-fatty-acid-complex',
                'category' => '4Life Fundamentals',
                'format' => 'softgels',
                'serving_size' => '2 softgels',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Fish Oil Blend (EPA + DHA)", "amount": "500", "unit": "mg", "details": "omega-3"}, {"name": "Flaxseed oil", "amount": null, "unit": "mg", "details": "omega-3"}, {"name": "Borage seed oil", "amount": null, "unit": "mg", "details": "omega-6 GLA"}, {"name": "Safflower seed oil", "amount": null, "unit": "mg", "details": "CLA"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Aceite de pescado 500mg EPA+DHA + linaza + borraja + cártamo (CLA).',
                'mechanism' => 'Omega-3 y omega-6 para salud cardiovascular y membranas celulares.',
                'dosage_instructions' => 'Tomar 2 cápsulas blandas al día con comida.',
                'benefits' => 'Soporte cardiovascular y cerebral con omega-3/6.',
                'warnings' => 'Contiene pescado.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Cal-Mag Complex',
                'slug' => 'cal-mag-complex',
                'category' => '4Life Fundamentals',
                'format' => 'tablets',
                'serving_size' => '3 tablets',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Calcium", "amount": "600", "unit": "mg", "details": null}, {"name": "Magnesium", "amount": "270", "unit": "mg", "details": null}, {"name": "Vitamin D", "amount": "400", "unit": "IU", "details": null}, {"name": "Vitamin C, K, zinc, boron", "amount": null, "unit": null, "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Calcio 600mg + magnesio 270mg + vitamina D 400IU + C, K, zinc, boro.',
                'mechanism' => 'Calcio y magnesio para metabolismo óseo. Vitamina D para absorción de calcio.',
                'dosage_instructions' => 'Tomar 3 tabletas al día.',
                'benefits' => 'Soporte para salud ósea y sistema estructural.',
                'warnings' => 'Contiene soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Fibro AMJ Day-Time Formula',
                'slug' => 'fibro-amj',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Vitamin B6 + Magnesium", "amount": null, "unit": "mg", "details": null}, {"name": "Joint Blend (glucosamine, MSM, bovine cartilage, Boswellia, bromelain, devils claw)", "amount": null, "unit": "mg", "details": null}, {"name": "Antioxidant Blend (malic acid, NAC, L-cysteine, grapeseed, ALA)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'B6 + magnesio + glucosamina + MSM + Boswellia + bromelina + garra del diablo + NAC + uva + ALA.',
                'mechanism' => 'B6 y magnesio para energía. Glucosamina y MSM para articulaciones. Boswellia para respaldo adicional.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día con comida.',
                'benefits' => 'Soporte para músculos, huesos, articulaciones y sistema nervioso.',
                'warnings' => 'Contiene mariscos (glucosamina) y cartílago bovino.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Flex4Life',
                'slug' => 'flex4life',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Avocado/soy seed extracts", "amount": null, "unit": "mg", "details": null}, {"name": "Hyaluronic acid", "amount": null, "unit": "mg", "details": null}, {"name": "Terminalia chebula", "amount": null, "unit": "mg", "details": null}, {"name": "Bromelain + trypsin", "amount": null, "unit": "mg", "details": null}, {"name": "Turmeric + Boswellia + black pepper", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Aguacate/soja + ácido hialurónico + Terminalia + bromelina + cúrcuma + Boswellia + pimienta negra.',
                'mechanism' => 'Respalda tejido articular, fluidos y flexibilidad. Terminalia, AH y cúrcuma para rodillas.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día.',
                'benefits' => 'Soporte para articulaciones flexibles y rango de movimiento.',
                'warnings' => 'Contiene soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Fortified Colostrum',
                'slug' => 'fortified-colostrum',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Colostrum powder", "amount": null, "unit": "mg", "details": "bovine"}, {"name": "Lactoferrin", "amount": null, "unit": "mg", "details": null}, {"name": "Oligosaccharides", "amount": null, "unit": "mg", "details": null}, {"name": "Alpha lactalbumin", "amount": null, "unit": "mg", "details": null}, {"name": "MFGM", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Calostro bovino + lactoferrina + oligosacáridos + alfa-lactalbúmina + MFGM. Para +4 años.',
                'mechanism' => 'Calostro bovino: respalda inmune, digestivo, microbiota, cerebro y respiratorio.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día.',
                'benefits' => 'Soporte inmune, digestivo, respiratorio y cerebral con calostro.',
                'warnings' => 'Contiene derivados de leche.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Gurmar',
                'slug' => 'gurmar',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '3 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Gymnema leaf + leaf extract", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Gymnema (hoja + extracto). Hierba antigua de la India.',
                'mechanism' => 'Respalda sistema endocrino para equilibrar glucosa.',
                'dosage_instructions' => 'Tomar 3 cápsulas al día.',
                'benefits' => 'Soporte para metabolismo de glucosa y control de peso.',
                'warnings' => 'Consultar médico si usa medicación para glucosa.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Life C Chewable',
                'slug' => 'life-c-chewable',
                'category' => '4Life Fundamentals',
                'format' => 'chewables',
                'serving_size' => '2 tablets',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Vitamin C (7 active forms)", "amount": null, "unit": "mg", "details": "calcium ascorbate, ascorbic acid, dehydroascorbic acid, erythorbic acid, magnesium ascorbate, ascorbyl palmitate, ascorbigen"}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Vitamina C en 7 formas activas naturales.',
                'mechanism' => 'Mezcla exclusiva de 7 formas de vitamina C para absorción optimizada y antioxidante amplio.',
                'dosage_instructions' => 'Tomar 2 tabletas masticables al día.',
                'benefits' => 'Antioxidante + respaldo inmune con vitamina C de alta absorción.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Menopause Support Formula',
                'slug' => 'menopause-support',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Hormone Balance Blend (soy, black cohosh, dong quai, chaste tree, turmeric)", "amount": null, "unit": "mg", "details": null}, {"name": "Female Blend (magnolia, eleuthero, quercetin, L-theanine)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Soja + cohosh negro + dong quai + árbol casto + cúrcuma + magnolia + eleutero + quercetina + L-teanina.',
                'mechanism' => 'Isoflavonas, cohosh negro y árbol casto para niveles hormonales. Antioxidantes de quercetina y cúrcuma.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día.',
                'benefits' => 'Soporte para menopausia, hormonas y estado anímico.',
                'warnings' => 'Contiene soja.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Multiplex',
                'slug' => 'multiplex',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Full multivitamin/mineral complex", "amount": null, "unit": null, "details": "A, C, D, E, B-complex, Ca, Fe, I, Mg, Zn, Se, Cu, Mn, Cr"}, {"name": "Proprietary Blend (citrus bioflavonoid, spirulina, PABA, rose hips)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Multivitamínico completo + bioflavonoides + spirulina + PABA + escaramujo.',
                'mechanism' => 'Dosis básica diaria de vitaminas y minerales esenciales. Hierbas y bioflavonoides para energía.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día con comida.',
                'benefits' => 'Multivitamínico diario básico.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'MusculoSkeletal Formula',
                'slug' => 'musculoskeletal-formula',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Alfalfa + gotu kola + devils claw + ginger + turmeric + saw palmetto", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Alfalfa + gotu kola + garra del diablo + jengibre + cúrcuma + palma enana.',
                'mechanism' => 'Respalda reparación de músculos, tendones, ligamentos, nervios. Estructura ósea. Tejido conectivo.',
                'dosage_instructions' => 'Tomar 2 cápsulas al día.',
                'benefits' => 'Soporte para músculos, huesos, articulaciones y tejido conectivo.',
                'warnings' => null,
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'Stress Formula',
                'slug' => 'stress-formula',
                'category' => '4Life Fundamentals',
                'format' => 'capsules',
                'serving_size' => '2 capsules',
                'servings_per_container' => 30,
                'ingredients' => json_encode(json_decode('[{"name": "Herbal Blend (valerian, peppermint, chamomile, passionflower, Ginkgo, linden, lemon balm, hops)", "amount": null, "unit": "mg", "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Valeriana + menta + manzanilla + pasiflora + ginkgo + tilo + melisa + lúpulo.',
                'mechanism' => 'Fórmula herbal calmante nocturna. Valeriana para sistema nervioso tranquilo. Menta calma estómago.',
                'dosage_instructions' => 'Tomar 2 cápsulas en la noche.',
                'benefits' => 'Soporte para relajación nocturna y manejo del estrés.',
                'warnings' => 'Puede causar somnolencia.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => '4Life Fortify',
                'slug' => '4life-fortify',
                'category' => '4Life Fundamentals',
                'format' => 'powder bag',
                'serving_size' => '1 meal',
                'servings_per_container' => 12,
                'ingredients' => json_encode(json_decode('[{"name": "Rice + lentils + beans", "amount": null, "unit": "g", "details": null}, {"name": "Vitamin/mineral complex + 4Life Transfer Factor", "amount": null, "unit": null, "details": null}]', true), JSON_UNESCAPED_UNICODE),
                'key_ingredients_summary' => 'Arroz + lentejas + frijoles + complejo vitamínico + Transfer Factor. 12-24 comidas.',
                'mechanism' => 'Comida rica en proteína con Transfer Factor. A través de Feed the Children.',
                'dosage_instructions' => 'Preparar según instrucciones. 1 comida completa.',
                'benefits' => 'Comida nutritiva con Transfer Factor para emergencia alimentaria.',
                'warnings' => 'Producto para donación. No para uso personal.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Oil-to-Foam Cleanser',
                'slug' => 'akwa-oil-to-foam-cleanser',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Agua de t\u00e9 verde fermentado + agua de mar + fermento de arroz. Vegano.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Agua de té verde fermentado + agua de mar + fermento de arroz. Vegano.',
                'mechanism' => 'Limpiador de dos fases. Fermento de arroz refina poros.',
                'dosage_instructions' => 'Aplicar sobre rostro húmedo, masajear y enjuagar.',
                'benefits' => 'Limpieza profunda sin resecar. Vegano.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Four-in-One Toner',
                'slug' => 'akwa-four-in-one-toner',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Agua de t\u00e9 verde fermentado + agua de rosas. Sin alcohol. Vegano.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Agua de té verde fermentado + agua de rosas. Sin alcohol. Vegano.',
                'mechanism' => 'Aclara, ilumina, prepara y fija maquillaje.',
                'dosage_instructions' => 'Rociar sobre rostro después de limpiar.',
                'benefits' => 'Tónico 4 en 1.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Vitamin Serum',
                'slug' => 'akwa-vitamin-serum',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Agua de t\u00e9 verde fermentado + arce rojo + vitaminas + fermentos + antioxidantes.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Agua de té verde fermentado + arce rojo + vitaminas + fermentos + antioxidantes.',
                'mechanism' => 'Nutre e hidrata. Respalda microbiota de la piel.',
                'dosage_instructions' => 'Aplicar sobre rostro limpio antes de crema.',
                'benefits' => 'Sérum nutritivo para tez juvenil.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Revitalizing Eye Cream',
                'slug' => 'akwa-revitalizing-eye-cream',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Agua de t\u00e9 verde fermentado + pepino + bamb\u00fa + hongo col\u00e1geno vegetal.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Agua de té verde fermentado + pepino + bambú + hongo colágeno vegetal.',
                'mechanism' => 'Reduce hinchazón, atenúa ojeras.',
                'dosage_instructions' => 'Aplicar alrededor del contorno de ojos.',
                'benefits' => 'Crema de ojos para hinchazón y ojeras.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Moisturizing Cream',
                'slug' => 'akwa-moisturizing-cream',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Agua de t\u00e9 verde fermentado + savia de abedul + ginseng.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Agua de té verde fermentado + savia de abedul + ginseng.',
                'mechanism' => 'Calma, hidrata intensamente, corrige arrugas.',
                'dosage_instructions' => 'Aplicar mañana y noche.',
                'benefits' => 'Hidratación intensa con corrección de arrugas.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Volcanic Mud Mask',
                'slug' => 'akwa-volcanic-mud-mask',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Agua de t\u00e9 verde fermentado + soya negra + ceniza volc\u00e1nica.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Agua de té verde fermentado + soya negra + ceniza volcánica.',
                'mechanism' => 'Ceniza volcánica limpia profundamente, exfolia.',
                'dosage_instructions' => 'Aplicar, dejar 10-15 min, enjuagar.',
                'benefits' => 'Mascarilla purificadora con ceniza volcánica.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä SPF 30 Moisturizing Sunscreen',
                'slug' => 'akwa-spf30-sunscreen',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Protector solar FPS 30. F\u00f3rmula ligera.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Protector solar FPS 30. Fórmula ligera.',
                'mechanism' => 'Protección contra factores ambientales y UV.',
                'dosage_instructions' => 'Aplicar antes de exposición solar. Reaplicar cada 2h.',
                'benefits' => 'Protección solar FPS 30 cremosa.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'äKwä Sheet Mask',
                'slug' => 'akwa-sheet-mask',
                'category' => 'äKwä Skincare',
                'format' => 'topical',
                'serving_size' => 'apply to skin',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "\u00danica mascarilla de velo con Transfer Factor de calostro y yema de huevo.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Única mascarilla de velo con Transfer Factor de calostro y yema de huevo.',
                'mechanism' => 'Hidratación intensa. Ilumina. Reduce líneas finas y arrugas.',
                'dosage_instructions' => 'Aplicar sobre rostro limpio, 15-20 min.',
                'benefits' => 'Mascarilla de velo con Transfer Factor.',
                'warnings' => 'Solo uso externo. Libre de parabenos, sulfatos y ftalatos.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'enummi Toothpaste',
                'slug' => 'enummi-toothpaste',
                'category' => 'enummi',
                'format' => 'personal care',
                'serving_size' => 'Cepillar dos veces al día',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Postbi\u00f3tico para inmunidad oral. Sin fluoruro.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Postbiótico para inmunidad oral. Sin fluoruro.',
                'mechanism' => 'Limpia dientes con postbiótico. Disuelve placa.',
                'dosage_instructions' => 'Cepillar dos veces al día.',
                'benefits' => 'Limpieza dental con postbiótico. Sin fluoruro.',
                'warnings' => 'Solo uso externo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'enummi Body Lotion',
                'slug' => 'enummi-body-lotion',
                'category' => 'enummi',
                'format' => 'personal care',
                'serving_size' => 'Aplicar sobre la piel del cuerpo',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "T\u00e9 blanco + aloe vera + manteca de karit\u00e9 + vitaminas.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Té blanco + aloe vera + manteca de karité + vitaminas.',
                'mechanism' => 'Protege de elementos ambientales. Suaviza y da tersura.',
                'dosage_instructions' => 'Aplicar sobre la piel del cuerpo.',
                'benefits' => 'Loción corporal suavizante.',
                'warnings' => 'Solo uso externo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'enummi Shower Gel',
                'slug' => 'enummi-shower-gel',
                'category' => 'enummi',
                'format' => 'personal care',
                'serving_size' => 'Aplicar en la ducha',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Mango + aguacate + miel. Gel con espuma lujosa.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Mango + aguacate + miel. Gel con espuma lujosa.',
                'mechanism' => 'Limpieza delicada para toda la familia.',
                'dosage_instructions' => 'Aplicar en la ducha.',
                'benefits' => 'Gel de baño hidratante.',
                'warnings' => 'Solo uso externo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'enummi Shampoo',
                'slug' => 'enummi-shampoo',
                'category' => 'enummi',
                'format' => 'personal care',
                'serving_size' => 'Aplicar sobre cabello húmedo',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Limpiadores de coco + prote\u00ednas + amino\u00e1cidos. Sin sulfatos.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Limpiadores de coco + proteínas + aminoácidos. Sin sulfatos.',
                'mechanism' => 'Limpieza suave. Previene pérdida de color. Mejora brillo.',
                'dosage_instructions' => 'Aplicar sobre cabello húmedo.',
                'benefits' => 'Champú sin sulfatos para uso diario.',
                'warnings' => 'Solo uso externo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

            [
                'name' => 'enummi Conditioner',
                'slug' => 'enummi-conditioner',
                'category' => 'enummi',
                'format' => 'personal care',
                'serving_size' => 'Aplicar después del champú, 1-3 min, enjuagar',
                'servings_per_container' => null,
                'ingredients' => '[{"name": "Prote\u00ednas + vitaminas + amino\u00e1cidos + aceites naturales.", "amount": null, "unit": null, "details": null}]',
                'key_ingredients_summary' => 'Proteínas + vitaminas + aminoácidos + aceites naturales.',
                'mechanism' => 'Mejora manejabilidad y suavidad. Reduce resequedad.',
                'dosage_instructions' => 'Aplicar después del champú, 1-3 min, enjuagar.',
                'benefits' => 'Acondicionador suavizante con brillo intenso.',
                'warnings' => 'Solo uso externo.',
                'source_url' => null,
                'image_url' => null,
                'is_active' => true,
            ],

        ];

        foreach ($products as $product) {
            FlProductReference::updateOrCreate(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}