<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FlProductsSpainSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224075',
                'name' => 'Transfer Factor Plus',
                'slug' => 'transfer-factor-plus',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-plus-tri-factor/89',
                'image_url' => 'https://media2.4life.com/products/plus_eu_pd.jpg?width=200&mode=crop&quality=80',
                'description' => '¡Nuestro producto estrella!. Complemento alimenticio con zinc, extractos vegetales y extractos de hongos para reforzar el sistema inmunitario',
                'price' => 6497,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 1,
            ],
            [
                'country_id' => 20,
                'reference_id' => 2,
                'external_id' => '103224070',
                'name' => 'Transfer Factor Tri-Factor',
                'slug' => 'transfer-factor-tri-factor',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-tri-factor/95',
                'image_url' => 'https://media2.4life.com/products/tri_factor_eu_pd.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con 4Life Transfer Factor™ de calostro bovino y yema de huevo',
                'price' => 5092,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 2,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103222003',
                'name' => 'ReCall',
                'slug' => 'recall',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-recall/90',
                'image_url' => 'https://media2.4life.com/products/ShoppingSection2025.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con ingredientes para el sistema nervioso',
                'price' => 5666,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 3,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103221010',
                'name' => 'BCV',
                'slug' => 'bcv',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-cardio/77',
                'image_url' => 'https://media2.4life.com/products/bcv_eu_pd.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con ingredientes para favorecer el sistema cardiovascular.Siente el ritmo de un estilo de vida saludable.',
                'price' => 6437,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'cardio',
                'sort_order' => 4,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224201',
                'name' => 'Renuvo',
                'slug' => 'renuvo',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-renuvo-new-label/423',
                'image_url' => 'https://media2.4life.com/products/renuvo_eu_pd.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con ingredientes con propiedades antioxidantes para protegerte contra los efectos del estrés',
                'price' => 5661,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 5,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103425404',
                'name' => 'Transfer Factor Colágeno',
                'slug' => 'transfer-factor-colageno',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-collagen/1533',
                'image_url' => 'https://media2.4life.com/products/TF_Collagen_EU_1000x1000_20220204032242.JPG?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con vitaminas A, C y biotina',
                'price' => 3922,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 6,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103423020',
                'name' => 'PRE/O',
                'slug' => 'preo',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/preo-biotics/1172',
                'image_url' => 'https://media2.4life.com/products/PRE_O_1000x1000_20220124084639.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con bifidobacterias, lactobacillus y oligosacáridos.',
                'price' => 4635,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'digestive',
                'sort_order' => 7,
            ],
            [
                'country_id' => 20,
                'reference_id' => 4,
                'external_id' => '103428136',
                'name' => '4Life TF-Boost',
                'slug' => '4life-tf-boost',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/immune-boost/3034',
                'image_url' => 'https://media2.4life.com/products/TF_Boost_Primary.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio para el sistema inmunitario',
                'price' => 2224,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 8,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103229001',
                'name' => 'GluCoach',
                'slug' => 'glucoach',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-glucoach/81',
                'image_url' => 'https://media2.4life.com/products/Glucoach_veggie_shopping_section.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con cromo y extractos vegetales para mantener los niveles de glucosa',
                'price' => 6437,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 9,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103222535',
                'name' => 'Belle Vie',
                'slug' => 'belle-vie',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-belle-vie/75',
                'image_url' => 'https://media2.4life.com/products/BelleVieShoppingSection2025.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con extractos vegetales que ayudan al bienestar de la mujer.',
                'price' => 5365,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 10,
            ],
            [
                'country_id' => 20,
                'reference_id' => 47,
                'external_id' => '103227563',
                'name' => 'Energy Go Stix Berry',
                'slug' => 'energy-go-stix-berry',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/energy-berry/1629',
                'image_url' => 'https://media2.4life.com/products/Berry_2025_A_20251001010956.jpg?width=200&mode=crop&quality=80',
                'description' => 'Fórmula mejoradaBebida energética lista para mezclar, con 4Life Transfer Factor®',
                'price' => 5273,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'sachets',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 11,
            ],
            [
                'country_id' => 20,
                'reference_id' => 6,
                'external_id' => '103224113',
                'name' => 'RioVida Stix',
                'slug' => 'riovida-stix',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-riovida-stix/102',
                'image_url' => 'https://media2.4life.com/products/EU_RiovidaStix_2025.jpg?width=200&mode=crop&quality=80',
                'description' => 'RioVida Stix',
                'price' => 3350,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'sachets',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 12,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224087',
                'name' => 'Glutamine Prime',
                'slug' => 'glutamine-prime',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/nano-factor-glutamine-prime/48',
                'image_url' => 'https://media2.4life.com/products/Glutamine_Prime_2025_mockup_1000x1000.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con glutamina para mantener la masa muscular y potenciar los mecanismos antioxidantes de tu cuerpo',
                'price' => 3746,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 13,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224080',
                'name' => 'Transfer Factor Classic',
                'slug' => 'transfer-factor-classic',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-classic/79',
                'image_url' => 'https://media2.4life.com/products/ClassicEU_ShoppingSection2025.jpg?width=200&mode=crop&quality=80',
                'description' => 'Un clásico de 4Life desde 1998. Complemento alimenticio con calostro bovino',
                'price' => 4565,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 14,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103222005',
                'name' => 'Reflexion',
                'slug' => 'reflexion',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/reflexion/810',
                'image_url' => 'https://media2.4life.com/products/REFLEXION2021_v2_20210726064719.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio para el estado de ánimo',
                'price' => 5425,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 15,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103226530',
                'name' => 'Ritestart unisex',
                'slug' => 'ritestart-unisex',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/ritestart-unisex/1514',
                'image_url' => 'https://media2.4life.com/products/RiteStart_1000x1000_20250702035000.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con vitaminas, minerales, ácidos grasos esenciales y extractos vegetales para el bienestar general',
                'price' => 7332,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 16,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103228148',
                'name' => 'AgePro',
                'slug' => 'agepro',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/agepro/3718',
                'image_url' => 'https://media2.4life.com/products/AgePro_frontal.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio diseñado para revitalizar y apoyar tu longevidad',
                'price' => 6086,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 17,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224110',
                'name' => 'RioVida Burst',
                'slug' => 'riovida-burst',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-riovida-burst/94',
                'image_url' => 'https://media2.4life.com/products/EU_BURST_2022_1000x1000_v1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio en gel a base de frutas y vitamina C',
                'price' => 4442,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 18,
            ],
            [
                'country_id' => 20,
                'reference_id' => 8,
                'external_id' => '103227577',
                'name' => 'Pro-TF Chocolate',
                'slug' => 'pro-tf-chocolate',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/pro-tfr-chocolate/662',
                'image_url' => 'https://media2.4life.com/products/Pro_TF_Chocolate_EU_2023_01.jpg?width=200&mode=crop&quality=80',
                'description' => 'Con proteínas hidrolizadas de alta calidad que contribuyen al aumento y el mantenimiento de la masa muscular',
                'price' => 6636,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 19,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103228095',
                'name' => 'Essential Fatty Acid Complex',
                'slug' => 'essential-fatty-acid-complex',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/bioefa-with-cla/3',
                'image_url' => 'https://media2.4life.com/products/Essential-Shopping-section.png?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con ácidos grasos esenciales para el bienestar cardiovascular',
                'price' => 2704,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'cardio',
                'sort_order' => 20,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103223015',
                'name' => 'Super Detox',
                'slug' => 'super-detox',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/digest4life-super-detox/1223',
                'image_url' => 'https://media2.4life.com/products/SuperDetoxEU_2025_ShoppingSection.jpg?width=200&mode=crop&quality=80',
                'description' => 'Contiene extractos de plantas (fruto de cardo mariano, hoja de diente de león y hoja de alcachofa) que contribuyen a mantener la función hepática normal.',
                'price' => 3160,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 21,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103229501',
                'name' => 'Vista',
                'slug' => 'vista',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-vista/96',
                'image_url' => 'https://media2.4life.com/products/Vista_2025_1000x1000.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con vitamina A, zinc y extractos vegetales para el funcionamiento normal de la vista',
                'price' => 5346,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 22,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224042',
                'name' => 'Transfer Factor Masticable',
                'slug' => 'transfer-factor-masticable',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-chewable/78',
                'image_url' => 'https://media2.4life.com/products/Chewable_1000x1000_a.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con calostro bovino y yema de huevo. La opción masticable para disfrutar de 4Life Transfer Factor con un delicioso sabor',
                'price' => 5209,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'chewables',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 23,
            ],
            [
                'country_id' => 20,
                'reference_id' => 8,
                'external_id' => '103227568',
                'name' => 'Pro-TF Vainilla',
                'slug' => 'pro-tf-vainilla',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/pro-tf-protein/361',
                'image_url' => 'https://media2.4life.com/products/Pro_TF_Vanilla_EU_2023_01.jpg?width=200&mode=crop&quality=80',
                'description' => 'Con proteínas hidrolizadas de alta calidad que contribuyen al aumento y el mantenimiento de la masa muscular',
                'price' => 6636,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 24,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103222562',
                'name' => 'MalePro',
                'slug' => 'malepro',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-malepro/87',
                'image_url' => 'https://media2.4life.com/products/Male_Pro_EU_1000x1000.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con minerales y extractos vegetales que ayudan al bienestar del hombre',
                'price' => 6321,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 25,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103221501',
                'name' => 'Lung',
                'slug' => 'lung',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/4life-transfer-factor-lung/2360',
                'image_url' => 'https://media2.4life.com/products/EU_TF_Lung.jpg?width=200&mode=crop&quality=80',
                'description' => 'Contiene ingredientes que promueven el bienestar del aparato respiratorio',
                'price' => 4507,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => false,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 26,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103224501',
                'name' => 'Fibro AMJ Day',
                'slug' => 'fibro-amj-day',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/fibro-amj-day-time-formula/33',
                'image_url' => 'https://media2.4life.com/products/EU_Fibro_AMJ_1000x1000_20210920020407.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con Magnesio y Boswellia para el buen mantenimiento de articulaciones, huesos y músculos',
                'price' => 2809,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 27,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103228134',
                'name' => 'Fibre System Plus',
                'slug' => 'fibre-system-plus',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/digest4life-fibre-system-plus/1222',
                'image_url' => 'https://media2.4life.com/products/Fibre_System_Plus_EU_2023.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con fibras vegetales que contribuyen a una digestión sana y a mantener la regularidad.',
                'price' => 4017,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'digestive',
                'sort_order' => 28,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103227584',
                'name' => 'Burn',
                'slug' => 'burn',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/burn/811',
                'image_url' => 'https://media2.4life.com/products/Burn_EU_2022_1000x1000_20220111095132.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con extractos vegetales que ayudan al metabolismo normal de la grasa y al control del peso corporal',
                'price' => 6389,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'weight',
                'sort_order' => 29,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225143',
                'name' => 'RainBurst Crema humectante',
                'slug' => 'rainburst-crema-humectante',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/akwa-moisture-cream/1528',
                'image_url' => 'https://media2.4life.com/products/rainburst_20200827164708.jpg?width=200&mode=crop&quality=80',
                'description' => 'Una crema similar a una nube que ayuda a calmar y renovar la piel para que luzca con una apariencia más joven',
                'price' => 3154,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'cream',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 30,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225003',
                'name' => 'Body Lotion',
                'slug' => 'body-lotion',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/enummi-intensive-body-lotion/20',
                'image_url' => 'https://media2.4life.com/products/body_lotion_1000x1000.jpg?width=200&mode=crop&quality=80',
                'description' => 'Con aloe vera y manteca de karité, esta crema corporal intensiva promueve una piel suave y tersa.',
                'price' => 2276,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'cream',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 31,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225041',
                'name' => 'RenewAll',
                'slug' => 'renewall',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/transfer-factor-renewall/91',
                'image_url' => 'https://media2.4life.com/products/EU_RenewAll_2023.jpg?width=200&mode=crop&quality=80',
                'description' => 'Gel calmante para la piel',
                'price' => 2511,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 32,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103227587',
                'name' => 'Energy Tropical',
                'slug' => 'energy-tropical',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/energy-tropical/1627',
                'image_url' => 'https://media2.4life.com/products/1.000x1.000_Tropical_EU_1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con cafeína y extractos vegetales que ayudan a la concentración, al estado de alerta y al rendimiento físico y mental.',
                'price' => 3043,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'energy',
                'sort_order' => 33,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225099',
                'name' => 'Toothpaste',
                'slug' => 'toothpaste',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/enummi-toothpaste/27',
                'image_url' => 'https://media2.4life.com/products/EU_toothpaste_1000x1000.jpg?width=200&mode=crop&quality=80',
                'description' => 'Descubre un lujo sin precedentes con el dentífrico enummi, el único con 4Life Transfer Factor y un postbiótico para un cuidado bucal avanzado.',
                'price' => 1545,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 34,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225139',
                'name' => 'Precious Pool',
                'slug' => 'precious-pool',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/akwa-vitamin-essence/1526',
                'image_url' => 'https://media2.4life.com/products/precious-pool_20200827164413.jpg?width=200&mode=crop&quality=80',
                'description' => 'Un sérum sedoso que impregna tu piel de vitaminas esenciales, fermentos y superantioxidantes',
                'price' => 4120,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 35,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103227016',
                'name' => '4LifeTransform Woman',
                'slug' => '4lifetransform-woman',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/woman/807',
                'image_url' => 'https://media2.4life.com/products/Woman_1000x1000.jpg?width=200&mode=crop&quality=80',
                'description' => ' ',
                'price' => 4571,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'weight',
                'sort_order' => 36,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225141',
                'name' => 'Crema de ojos Ripple Refine',
                'slug' => 'crema-de-ojos-ripple-refine',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/akwa-eye-cream/1527',
                'image_url' => 'https://media2.4life.com/products/ripple-refine_20200827164533.jpg?width=200&mode=crop&quality=80',
                'description' => 'Promueve una apariencia del contorno de los ojos más suave y con aspecto más juvenil con un hongo ancestral',
                'price' => 4248,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'cream',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 37,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103226535',
                'name' => '4LIFETRANSFORM MAN',
                'slug' => '4lifetransform-man',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/man/805',
                'image_url' => 'https://media2.4life.com/products/Man_1000x1000_20210706014851.JPG?width=200&mode=crop&quality=80',
                'description' => 'Complemento alimenticio con Panax Ginseng para el mantenimiento de la salud sexual.',
                'price' => 4038,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'weight',
                'sort_order' => 38,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225133',
                'name' => 'First Wave',
                'slug' => 'first-wave',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/akwa-oil-to-foam-cleanser/1523',
                'image_url' => 'https://media2.4life.com/products/first-wave_20200827163340.jpg?width=200&mode=crop&quality=80',
                'description' => 'Una fórmula cristalina que se desliza en la piel como un aceite ligero, que luego se transforma en una espuma fina y suave, y se enjuaga con facilidad.',
                'price' => 3090,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 39,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225135',
                'name' => 'Glacier Glow',
                'slug' => 'glacier-glow',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/akwa-four-way-toner/1524',
                'image_url' => 'https://media2.4life.com/products/glacier-glow_20200827164049.jpg?width=200&mode=crop&quality=80',
                'description' => 'Tónico sin alcohol que prepara tu piel para una limpieza y humectación adicionales y para la aplicación de cosméticos',
                'price' => 3219,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 40,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '103225145',
                'name' => 'Mascarilla facial de velo Royal Bath',
                'slug' => 'mascarilla-facial-de-velo-royal-bath',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/akwa-sheet-mask/1529',
                'image_url' => 'https://media2.4life.com/products/royal-bath_20200827164941.jpg?width=200&mode=crop&quality=80',
                'description' => 'Un tratamiento exclusivo que, según la historia, solo podía disfrutar la realeza en el pasado.',
                'price' => 3284,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 41,
            ],
            [
                'country_id' => 20,
                'reference_id' => null,
                'external_id' => '100015005',
                'name' => '4Life Fortify',
                'slug' => '4life-fortify',
                'url' => 'https://spain.4life.com/pepeyclaudia/product/fortify/37',
                'image_url' => 'https://media2.4life.com/products/fortifynewpackage_20200228154848_20200306035034.jpg?width=200&mode=crop&quality=80',
                'description' => ' ',
                'price' => 4043,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'EUR',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 42,
            ],
        ];

        $now = now();
        $rows = array_map(function ($row) use ($now) {
            $row['created_at'] = $row['created_at'] ?? $now;
            $row['updated_at'] = $now;
            return $row;
        }, $rows);

        DB::table('fl_products')->upsert(
            $rows,
            ['country_id', 'external_id'],
            [
                'reference_id',
                'name',
                'slug',
                'url',
                'image_url',
                'description',
                'price',
                'price_wholesale',
                'price_loyalty',
                'currency_code',
                'format',
                'units_per_container',
                'serving_size',
                'is_pack',
                'is_available',
                'is_on_promotion',
                'promotion_details',
                'category',
                'sort_order',
                'updated_at',
            ]
        );
    }
}
