<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FlProductsMexicoSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'country_id' => 37,
                'reference_id' => 47,
                'external_id' => '90227563',
                'name' => 'Energy Go Stix',
                'slug' => 'energy-go-stix',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/energy-go-stix-mex/4197',
                'image_url' => 'https://media2.4life.com/products/ENERGYGOSTIX1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Delicioso respaldo en prácticos paquetes de polvo
listo para mezclar.',
                'price' => 109800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'energy',
                'sort_order' => 1,
            ],
            [
                'country_id' => 37,
                'reference_id' => 1,
                'external_id' => '90224075',
                'name' => '4Life Plus',
                'slug' => '4life-plus',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-plus-tri-factor/89',
                'image_url' => 'https://media2.4life.com/products/PLUS1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Nuestro producto principal contiene la exclusiva 4Life Tri-FactorTM Formula, una mezcla exclusiva de hongos y zinc.',
                'price' => 107100,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 2,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90221010',
                'name' => '4Life TF BCV Tri-Factor Formula®',
                'slug' => '4life-tf-bcv-tri-factor-formula',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/90221010/3975',
                'image_url' => 'https://media2.4life.com/products/NUEVOBCV.jpg?width=200&mode=crop&quality=80',
                'description' => 'Fórmula con una amplia gama de vitaminas, magnesio, antioxidantes y la exclusiva 4Life Tri-Factor Formula, que ayuda a complementar tu alimentación diaria.',
                'price' => 109200,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 3,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224201',
                'name' => '4Life Renuvo',
                'slug' => '4life-renuvo',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4life-renuvo-120-capsules/881',
                'image_url' => 'https://media2.4life.com/products/RENUVOWEB1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Fórmula a base de vegetales y la exclusiva 4Life Tri-FactorTM Formula (mezcla de proteínas de calostro bovino ultra y nanofiltrado y yema de huevo).',
                'price' => 94400,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 4,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90222535',
                'name' => '4Life Belle Vie',
                'slug' => '4life-belle-vie',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4life-belle-vie/535',
                'image_url' => 'https://media2.4life.com/products/BELLEVIE1_20250602181208.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas',
                'price' => 89700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 5,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224070',
                'name' => '4Life Avanzado',
                'slug' => '4life-avanzado',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-tri-factor/95',
                'image_url' => 'https://media2.4life.com/products/Mexico_avanzado_image.png?width=200&mode=crop&quality=80',
                'description' => 'Suplemento Alimenticio con la exclusiva 4Life Tri-FactorTM Formula, proveniente del calostro bovino y yema de huevo.',
                'price' => 80600,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 6,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224141',
                'name' => 'RioVida Jugo',
                'slug' => 'riovida-jugo',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/riovida-jugo/4461',
                'image_url' => 'https://media2.4life.com/products/RIOVIDAJUGO1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Una deliciosa bebida que incluye una mezcla exclusiva de jugos naturales de frutas ricas en antioxidantes y la 4Life Tri-Factor Formula',
                'price' => 78700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 7,
            ],
            [
                'country_id' => 37,
                'reference_id' => 25,
                'external_id' => '90225404',
                'name' => '4Life Collagen',
                'slug' => '4life-collagen',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4life-collagen-mex/1835',
                'image_url' => 'https://media2.4life.com/products/0_20221103114042.jpg?width=200&mode=crop&quality=80',
                'description' => 'Colágeno hidrolizado premium tipo I, acompañado de la exclusiva 4Life Tri-FactorTM Formula (mezcla de proteínas de calostro bovino ultra y nanofiltrado y yema de huevo), vitaminas C y E para complementar tu alimentación.',
                'price' => 69000,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 8,
            ],
            [
                'country_id' => 37,
                'reference_id' => 6,
                'external_id' => '90224113',
                'name' => '4Life RioVida StixTM',
                'slug' => '4life-riovida-stixtm',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-riovida-stix/102',
                'image_url' => 'https://media2.4life.com/products/RIOVIDASTIX1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Deliciosa bebida no alcohólica para preparar, en un paquete de porciones individuales fácil de llevar, en polvo que contiene manzana, granada, mora azul, uva, saúco rojo y acaí. Adicionado con 4Life Tri-FactorTM Formula Formula.',
                'price' => 57000,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 9,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90228148',
                'name' => '4Life TF AG-ProTM',
                'slug' => '4life-tf-ag-protm',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/tf-ag-pro/3838',
                'image_url' => 'https://media2.4life.com/products/AGPRO1.jpg?width=200&mode=crop&quality=80',
                'description' => '¡Conoce nuestro nuevo producto!',
                'price' => 105100,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'immune',
                'sort_order' => 10,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90228095',
                'name' => 'BioEFA',
                'slug' => 'bioefa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/bioefa-with-cla/3',
                'image_url' => 'https://media2.4life.com/products/BIOEFA1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Ácidos grasos esenciales Omega-3 y Omega-6 para proveer un complemento a tu nutrición diaria.',
                'price' => 44200,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 11,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224110',
                'name' => '4Life RioVida Burst',
                'slug' => '4life-riovida-burst',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-riovida-burst/94',
                'image_url' => 'https://media2.4life.com/products/RIOVIDABURST1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en gel, práctico y delicioso.',
                'price' => 73900,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 12,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90228087',
                'name' => 'NutraStart® Chocolate',
                'slug' => 'nutrastart-chocolate',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/nutrastart-chocolate/49',
                'image_url' => 'https://media2.4life.com/products/NUTRASTARTWEB1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en polvo para preparar una bebida de complementación nutricional que incluye la 4Life Formula®, vitaminas y minerales.',
                'price' => 96200,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 13,
            ],
            [
                'country_id' => 37,
                'reference_id' => 4,
                'external_id' => '90228136',
                'name' => '4Life TF-Boost®',
                'slug' => '4life-tf-boost',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/tf-boost---mex/3552',
                'image_url' => 'https://media2.4life.com/products/TF_BOOST.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en polvo para preparar una bebida sabor a naranja.',
                'price' => 40100,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 14,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90229501',
                'name' => '4Life Vistari',
                'slug' => '4life-vistari',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4life-vistari/543',
                'image_url' => 'https://media2.4life.com/products/Mexico-vistari-new.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas',
                'price' => 96500,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 15,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90222005',
                'name' => '4Life Reflexion',
                'slug' => '4life-reflexion',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4life-reflexion/2606',
                'image_url' => 'https://media2.4life.com/products/Mexico-Reflexion web_20220124085919.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas',
                'price' => 103900,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 16,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224042',
                'name' => '4Life Masticable®',
                'slug' => '4life-masticable',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-chewable/78',
                'image_url' => 'https://media2.4life.com/products/MASTICABLE1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Tabletas masticables con la exclusiva 4Life Tri-FactorTM Formula (mezcla de proteínas de calostro bovino ultra y nanofiltradas y yema de huevo).',
                'price' => 84700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'tablets',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 17,
            ],
            [
                'country_id' => 37,
                'reference_id' => 10,
                'external_id' => '90223020',
                'name' => 'Pre/o BioticsTM',
                'slug' => 'preo-bioticstm',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/preo-biotics/1807',
                'image_url' => 'https://media2.4life.com/products/PREOBIOTICSWEB1.jpg?width=200&mode=crop&quality=80',
                'description' => 'El único producto Prebiótico/Probiótico en el mundo que contiene la exclusiva 4Life Tri-FactorTM Formula.',
                'price' => 91600,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'digestive',
                'sort_order' => 18,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90228123',
                'name' => 'Gold FactorTM',
                'slug' => 'gold-factortm',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/gold-factor/2777',
                'image_url' => 'https://media2.4life.com/products/GOLD_FACTOR_WEB.jpg?width=200&mode=crop&quality=80',
                'description' => 'Delicada bebida con partículas de Oro Comestible ultrafinas, suspendidas en agua ultrapura.',
                'price' => 108700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 19,
            ],
            [
                'country_id' => 37,
                'reference_id' => 8,
                'external_id' => '90227577',
                'name' => 'Pro-TF® Chocolate',
                'slug' => 'pro-tf-chocolate',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/pro-tf-chocolate/1141',
                'image_url' => 'https://media2.4life.com/products/PROTFCHOCOLATE1_20250120090102.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en polvo a base de proteínas, sabor chocolate.',
                'price' => 117800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 20,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90223031',
                'name' => 'Aloe Vera Stix Tropical®',
                'slug' => 'aloe-vera-stix-tropical',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/aloe-vera-stix-tropical-mexico/3188',
                'image_url' => 'https://media2.4life.com/products/ALOEVERAWEB1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en polvo.',
                'price' => 57700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 21,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90221501',
                'name' => '4Life Respari',
                'slug' => '4life-respari',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4life-resparir/3292',
                'image_url' => 'https://media2.4life.com/products/RESPARI1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas',
                'price' => 80600,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 22,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224087',
                'name' => '4Life Glutamine Prime®',
                'slug' => '4life-glutamine-prime',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4lifer-glutamine/3291',
                'image_url' => 'https://media2.4life.com/products/GLUTAMINEWEB1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas.',
                'price' => 61900,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 23,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225003',
                'name' => 'Fórmula Concentrada',
                'slug' => 'formula-concentrada',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/enummi-intensive-body-lotion/20',
                'image_url' => 'https://media2.4life.com/products/crema 0_20211112153605.jpg?width=200&mode=crop&quality=80',
                'description' => 'Loción corporal concentrada que promueve una piel suave y tersa.',
                'price' => 34700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 24,
            ],
            [
                'country_id' => 37,
                'reference_id' => 8,
                'external_id' => '90227568',
                'name' => 'Pro-TF® Vainilla',
                'slug' => 'pro-tf-vainilla',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/pro-tf-protein/361',
                'image_url' => 'https://media2.4life.com/products/PROTFVAINILLA1_20250425132335.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en polvo a base de proteínas, sabor vainilla.',
                'price' => 117800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 25,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90226535',
                'name' => '4Life TForm Man®',
                'slug' => '4life-tform-man',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transform-man/1884',
                'image_url' => 'https://media2.4life.com/products/MAN_WEB_1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas.',
                'price' => 78400,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 26,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225143',
                'name' => 'Crema Humectante - äKwä®',
                'slug' => 'crema-humectante-akwa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/akwa-moisture-cream/1767',
                'image_url' => 'https://media2.4life.com/products/0_20210108134636.jpg?width=200&mode=crop&quality=80',
                'description' => 'Una crema inspirada en una nube de lluvia lista para estallar, esta crema ofrece una oleada de hidratación intensa en una fórmula ligera y aireada. Es verdaderamente una delicia para tu piel.',
                'price' => 49100,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'cream',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 27,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225041',
                'name' => '4Life RENEWALL®',
                'slug' => '4life-renewall',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-renewall/91',
                'image_url' => 'https://media2.4life.com/products/Mexico_renewall_new.png?width=200&mode=crop&quality=80',
                'description' => 'Gel corporal para uso en pieles sensibles y muy resecas, ideal para después de asolearse.',
                'price' => 37400,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 28,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224080',
                'name' => '4Life Clásico',
                'slug' => '4life-clasico',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/transfer-factor-classic/79',
                'image_url' => 'https://media2.4life.com/products/Mexico_clasico_single.png?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas.',
                'price' => 76800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 29,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225141',
                'name' => 'Crema para el contorno de los ojos - äKwä®',
                'slug' => 'crema-para-el-contorno-de-los-ojos-akwa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/akwa-refine-eye-cream/1766',
                'image_url' => 'https://media2.4life.com/products/0_20210108134926.jpg?width=200&mode=crop&quality=80',
                'description' => 'Promueve una apariencia del contorno de los ojos más suave y con aspecto terso con un hongo ancestral.',
                'price' => 61400,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'cream',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 30,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225139',
                'name' => 'Suero para uso facial de vitaminas - äKwä®',
                'slug' => 'suero-para-uso-facial-de-vitaminas-akwa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/akwa-vitamin-essence/1765',
                'image_url' => 'https://media2.4life.com/products/0_20210108135146.jpg?width=200&mode=crop&quality=80',
                'description' => 'Un sérum sedoso que impregna tu piel de vitaminas esenciales, fermentos y súper antioxidantes.',
                'price' => 59800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 31,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90224204',
                'name' => '4Life Transform PrezoomTM',
                'slug' => '4life-transform-prezoomtm',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/4lifetransform-prezoom/3679',
                'image_url' => 'https://media2.4life.com/products/Prezoom.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en polvo, sabor sandía.',
                'price' => 101700,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'powder',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'weight',
                'sort_order' => 32,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225099',
                'name' => 'enummi® Pasta Dental',
                'slug' => 'enummi-pasta-dental',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/enummi-toothpaste-single/887',
                'image_url' => 'https://media2.4life.com/products/PASTA1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Fórmula libre de flúor que refresca el aliento.',
                'price' => 30600,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 33,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225133',
                'name' => 'Limpiador de aceite con efecto espumoso - äKwä®',
                'slug' => 'limpiador-de-aceite-con-efecto-espumoso-akwa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/oil-to-foam-cleanser/1763',
                'image_url' => 'https://media2.4life.com/products/0_20210108135559.jpg?width=200&mode=crop&quality=80',
                'description' => 'Una fórmula cristalina que se desliza en la piel como un aceite ligero, que luego se transforma en un espuma fina y suave, y se enjuaga con facilidad.',
                'price' => 49100,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 34,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225135',
                'name' => 'Tónico cuatro en uno - äKwä®',
                'slug' => 'tonico-cuatro-en-uno-akwa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/akwa-four-way-toner/1764',
                'image_url' => 'https://media2.4life.com/products/0_20210108140142.jpg?width=200&mode=crop&quality=80',
                'description' => 'Tónico sin alcohol que prepara tu piel para una limpieza y humectación adicionales y la aplicación de cosméticos.',
                'price' => 53300,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'skin',
                'sort_order' => 35,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90225145',
                'name' => 'Mascarilla hidratante en velo – äKwä®',
                'slug' => 'mascarilla-hidratante-en-velo-akwa',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/akwa-sheet-mask/1769',
                'image_url' => 'https://media2.4life.com/products/MASCARILLA_1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Un tratamiento exclusivo que, de acuerdo a la historia, en algún momento solo fue disfrutando por la realeza.',
                'price' => 53800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => true,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 36,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90229001',
                'name' => '4Life GL-Coach',
                'slug' => '4life-gl-coach',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/tf-glucoach/1620',
                'image_url' => 'https://media2.4life.com/products/GLCOACHWEB1.jpg?width=200&mode=crop&quality=80',
                'description' => 'Suplemento alimenticio en cápsulas',
                'price' => 109800,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'capsules',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => false,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 37,
            ],
            [
                'country_id' => 37,
                'reference_id' => null,
                'external_id' => '90213004',
                'name' => 'Tea4Life',
                'slug' => 'tea4life',
                'url' => 'https://mexico.4life.com/pepeyclaudia/product/tea4life/72',
                'image_url' => 'https://media2.4life.com/products/TEA4LIFEWEB.jpg?width=200&mode=crop&quality=80',
                'description' => 'Una mezcla de hierbas para infusión con un delicioso sabor a manzana y canela.',
                'price' => 45400,
                'price_wholesale' => null,
                'price_loyalty' => null,
                'currency_code' => 'MXN',
                'format' => 'other',
                'units_per_container' => null,
                'serving_size' => null,
                'is_pack' => false,
                'is_available' => false,
                'is_on_promotion' => true,
                'promotion_details' => null,
                'category' => 'general',
                'sort_order' => 38,
            ],
        ];

        $now = now();
        $rows = array_map(function ($row) use ($now) {
            $row['created_at'] = $row['created_at'] ?? $now;
            $row['updated_at'] = $now;
            return $row;
        }, $rows);

        DB::table('fl_products')->upsert(
            $rows,
            ['country_id', 'external_id'],
            [
                'reference_id',
                'name',
                'slug',
                'url',
                'image_url',
                'description',
                'price',
                'price_wholesale',
                'price_loyalty',
                'currency_code',
                'format',
                'units_per_container',
                'serving_size',
                'is_pack',
                'is_available',
                'is_on_promotion',
                'promotion_details',
                'category',
                'sort_order',
                'updated_at',
            ]
        );
    }
}
