<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FlProductReference;
use Illuminate\Support\Facades\DB;

class FlProductAliasesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('fl_product_aliases')->truncate();

        $aliases = [
            ['country_id' => 20, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => 'Transfer Factor Plus', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => 'Transfer Factor Tri-Factor', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-recall', 'local_name' => 'ReCall', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-cardio', 'local_name' => 'BCV', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => 'Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-collagen', 'local_name' => 'Transfer Factor Colágeno', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'tf-boost-sachets', 'local_name' => '4Life TF-Boost', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'pre-o-biotics', 'local_name' => 'PRE/O', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-glucoach', 'local_name' => 'GluCoach', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => 'Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix Berry', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'riovida-stix', 'local_name' => 'RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'nanofactor-glutamine-prime', 'local_name' => 'Glutamine Prime', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-classic', 'local_name' => 'Transfer Factor Classic', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'ritestart', 'local_name' => 'RiteStart unisex', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-reflexion', 'local_name' => 'Reflexion', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-agepro', 'local_name' => 'AgePro', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'riovida-burst', 'local_name' => 'RioVida Burst', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Chocolate', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Vainilla', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'essential-fatty-acid-complex', 'local_name' => 'Essential Fatty Acid Complex', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'super-detox', 'local_name' => 'Super Detox', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-vista', 'local_name' => 'Vista', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-chewable', 'local_name' => 'Transfer Factor Masticable', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-lung', 'local_name' => 'Lung', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-malepro', 'local_name' => 'MalePro', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'fibro-amj', 'local_name' => 'Fibro AMJ Day', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'fibre-system-plus', 'local_name' => 'Fibre System Plus', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transform-burn', 'local_name' => 'Burn', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'akwa-moisturizing-cream', 'local_name' => 'RainBurst Crema humectante', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'enummi-body-lotion', 'local_name' => 'Body Lotion', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transfer-factor-renewall', 'local_name' => 'RenewAll', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Tropical', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'enummi-toothpaste', 'local_name' => 'Toothpaste', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'akwa-vitamin-serum', 'local_name' => 'Precious Pool', 'match_confidence' => 'similar'],
            ['country_id' => 20, 'product_slug' => 'akwa-revitalizing-eye-cream', 'local_name' => 'Crema de ojos Ripple Refine', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transform-woman', 'local_name' => '4LifeTransform Woman', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'transform-man', 'local_name' => '4LIFETRANSFORM MAN', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'akwa-oil-to-foam-cleanser', 'local_name' => 'First Wave', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'akwa-four-in-one-toner', 'local_name' => 'Glacier Glow', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => 'akwa-sheet-mask', 'local_name' => 'Mascarilla facial de velo Royal Bath', 'match_confidence' => 'exact'],
            ['country_id' => 20, 'product_slug' => '4life-fortify', 'local_name' => '4Life Fortify', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => '4Life Transfer Factor Plus Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => '4Life Transfer Factor Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-classic', 'local_name' => '4Life Transfer Factor Classic', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-chewable', 'local_name' => '4Life Transfer Factor Chewable Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-immune-spray', 'local_name' => '4Life Transfer Factor Immune Spray', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-renewall', 'local_name' => '4Life Transfer Factor RenewAll', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-immune-boost', 'local_name' => '4Life Transfer Factor Immune Boost', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-cardio', 'local_name' => '4Life Transfer Factor Cardio', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-recall', 'local_name' => '4Life Transfer Factor ReCall', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-glucoach', 'local_name' => '4Life Transfer Factor GluCoach', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-agepro', 'local_name' => '4Life Transfer Factor AgePro', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-collagen', 'local_name' => '4Life Transfer Factor Colágeno', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-collagen-type-i', 'local_name' => '4Life Transfer Factor Colágeno Tipo I', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'nanofactor-glutamine-prime', 'local_name' => '4Life NanoFactor Glutamine Prime', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-metabolite', 'local_name' => '4Life Transfer Factor Metabolite', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-kbu', 'local_name' => '4Life Transfer Factor KBU', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-lung', 'local_name' => '4Life Transfer Factor Lung', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-vista', 'local_name' => '4Life Transfer Factor Vista', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => '4Life Transfer Factor Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-malepro', 'local_name' => '4Life Transfer Factor MalePro', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-reflexion', 'local_name' => '4Life Transfer Factor Reflexion', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-sleeprite', 'local_name' => '4Life Transfer Factor SleepRite', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'riovida-stix', 'local_name' => '4Life Transfer Factor RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'riovida-burst', 'local_name' => '4Life Transfer Factor RioVida Burst', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'riovida-chews', 'local_name' => '4Life Transfer Factor RioVida Chews', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'riovida-liquid', 'local_name' => '4Life Transfer Factor RioVida', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'ritestart', 'local_name' => 'RiteStart', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'ritestart-kids-teens', 'local_name' => 'RiteStart Niños y Adolescentes', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'nutrastart-blue-vanilla', 'local_name' => 'NutraStart Blue Vanilla', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Digest4Life Pre/o Biotics', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'aloe-vera-stix', 'local_name' => 'Digest4Life Aloe Vera Stix', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'digestive-enzymes', 'local_name' => 'Digest4Life Digestive Enzymes', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'fibre-system-plus', 'local_name' => 'Fibre System Plus', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'super-detox', 'local_name' => 'Digest4Life Super Detox', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'phytolax', 'local_name' => 'PhytoLax', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'tea4life', 'local_name' => 'Tea4Life', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Vainilla', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Chocolate', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transform-prezoom', 'local_name' => '4LifeTransform PreZoom', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => '4Life Transfer Factor Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transform-burn', 'local_name' => '4LifeTransform Burn', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'shaperite', 'local_name' => 'ShapeRite', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transform-woman', 'local_name' => '4LifeTransform Mujer', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transform-man', 'local_name' => '4LifeTransform Hombre', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'transform-protein-bar', 'local_name' => '4LifeTransform Protein Bar', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'zinc-factor', 'local_name' => 'Zinc Factor', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'gold-factor', 'local_name' => 'Gold Factor', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'essential-fatty-acid-complex', 'local_name' => 'Essential Fatty Acid Complex', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'cal-mag-complex', 'local_name' => 'Cal-Mag Complex', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'fibro-amj', 'local_name' => 'Fibro AMJ Fórmula Diurna', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'flex4life', 'local_name' => 'Flex4Life', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'fortified-colostrum', 'local_name' => 'Fortified Colostrum', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'gurmar', 'local_name' => 'Gurmar', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'life-c-chewable', 'local_name' => 'Life C Chewable', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'menopause-support', 'local_name' => 'Menopause Support Formula', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'multiplex', 'local_name' => 'Multiplex', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'musculoskeletal-formula', 'local_name' => 'MusculoSkeletal Formula', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'stress-formula', 'local_name' => 'Stress Formula', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => '4life-fortify', 'local_name' => '4Life Fortify', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'enummi-toothpaste', 'local_name' => 'enummi Pasta Dental', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'enummi-body-lotion', 'local_name' => 'enummi Loción Corporal', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'enummi-shower-gel', 'local_name' => 'enummi Gel de Baño', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'enummi-shampoo', 'local_name' => 'enummi Champú', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'enummi-conditioner', 'local_name' => 'enummi Acondicionador', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-oil-to-foam-cleanser', 'local_name' => 'äKwä Limpiador de Aceite a Espuma', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-four-in-one-toner', 'local_name' => 'äKwä Tónico Cuatro en Uno', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-vitamin-serum', 'local_name' => 'äKwä Sérum de Vitaminas', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-revitalizing-eye-cream', 'local_name' => 'äKwä Crema Reafirmante de Ojos', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-moisturizing-cream', 'local_name' => 'äKwä Crema Humectante', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-volcanic-mud-mask', 'local_name' => 'äKwä Mascarilla de Barro Volcánico', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-spf30-sunscreen', 'local_name' => 'äKwä Protector Solar FPS 30', 'match_confidence' => 'exact'],
            ['country_id' => 56, 'product_slug' => 'akwa-sheet-mask', 'local_name' => 'äKwä Mascarilla de Velo', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => 'Transfer Factor Plus', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-cardio', 'local_name' => 'BCV+', 'match_confidence' => 'similar'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => 'Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => 'Transfer Factor Tri-Factor', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => 'Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'riovida-stix', 'local_name' => 'RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'essential-fatty-acid-complex', 'local_name' => 'BioEFA', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-collagen', 'local_name' => 'Collagen', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-vista', 'local_name' => 'Vistari', 'match_confidence' => 'similar'],
            ['country_id' => 11, 'product_slug' => 'riovida-burst', 'local_name' => 'RioVida Burst', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'fibre-system-plus', 'local_name' => 'Fibre System', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'nutrastart-blue-vanilla', 'local_name' => 'NutraStart', 'match_confidence' => 'similar'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-reflexion', 'local_name' => 'Reflexion', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'super-detox', 'local_name' => 'LivRite', 'match_confidence' => 'similar'],
            ['country_id' => 11, 'product_slug' => 'tf-boost-sachets', 'local_name' => 'TF-Boost', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Pre/O Biotics', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Vainilla', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'nanofactor-glutamine-prime', 'local_name' => 'Glutamine Prime', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-chewable', 'local_name' => 'Chewable', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'aloe-vera-stix', 'local_name' => 'Aloe Vera Stix Tropical', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Chocolate', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-renewall', 'local_name' => 'RenewAll', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'enummi-body-lotion', 'local_name' => 'enummi Intensive Body Lotion', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'enummi-toothpaste', 'local_name' => 'enummi Toothpaste', 'match_confidence' => 'exact'],
            ['country_id' => 11, 'product_slug' => 'transfer-factor-immune-spray', 'local_name' => 'Oral Spray', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => 'Transfer Factor Plus', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => 'Transfer Factor Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'transfer-factor-cardio', 'local_name' => 'Transfer Factor BCV', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => 'Transfer Factor Tri-Factor', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'transfer-factor-agepro', 'local_name' => 'Transfer Factor AG-Pro', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'riovida-stix', 'local_name' => 'RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix - Berry', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'fibre-system-plus', 'local_name' => 'Fibre System Plus', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'tea4life', 'local_name' => 'Tea4Life', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Pre/O Biotics', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'tf-boost-sachets', 'local_name' => '4Life TF-Boost', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'pro-tf-protein', 'local_name' => 'PRO-TF Proteína', 'match_confidence' => 'exact'],
            ['country_id' => 12, 'product_slug' => 'transfer-factor-collagen', 'local_name' => 'Collagen', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => '4Life Plus', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-cardio', 'local_name' => '4Life TF BCV Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => '4Life Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => '4Life Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => '4Life Avanzado', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'riovida-liquid', 'local_name' => 'RioVida Jugo', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-collagen', 'local_name' => '4Life Collagen', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'riovida-stix', 'local_name' => '4Life RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-agepro', 'local_name' => '4Life TF AG-Pro', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'essential-fatty-acid-complex', 'local_name' => 'BioEFA', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'riovida-burst', 'local_name' => '4Life RioVida Burst', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'nutrastart-blue-vanilla', 'local_name' => 'NutraStart Chocolate', 'match_confidence' => 'similar'],
            ['country_id' => 37, 'product_slug' => 'tf-boost-sachets', 'local_name' => '4Life TF-Boost', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-vista', 'local_name' => '4Life Vistari', 'match_confidence' => 'similar'],
            ['country_id' => 37, 'product_slug' => 'gold-factor', 'local_name' => 'Gold Factor', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-reflexion', 'local_name' => '4Life Reflexion', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-chewable', 'local_name' => '4Life Masticable', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Pre/o Biotics', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Chocolate', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Vainilla', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'aloe-vera-stix', 'local_name' => 'Aloe Vera Stix Tropical', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-lung', 'local_name' => '4Life Respari', 'match_confidence' => 'similar'],
            ['country_id' => 37, 'product_slug' => 'nanofactor-glutamine-prime', 'local_name' => '4Life Glutamine Prime', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'enummi-body-lotion', 'local_name' => 'Fórmula Concentrada', 'match_confidence' => 'similar'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-renewall', 'local_name' => '4Life RENEWALL', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-classic', 'local_name' => '4Life Clásico', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transform-prezoom', 'local_name' => '4Life Transform Prezoom', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'enummi-toothpaste', 'local_name' => 'enummi Pasta Dental', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transform-man', 'local_name' => '4Life TForm Man', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'akwa-moisturizing-cream', 'local_name' => 'Crema Humectante - äKwä', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'akwa-revitalizing-eye-cream', 'local_name' => 'Crema para el contorno de los ojos - äKwä', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'akwa-vitamin-serum', 'local_name' => 'Suero para uso facial de vitaminas - äKwä', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'akwa-oil-to-foam-cleanser', 'local_name' => 'Limpiador de aceite con efecto espumoso - äKwä', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'akwa-four-in-one-toner', 'local_name' => 'Tónico cuatro en uno - äKwä', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'akwa-sheet-mask', 'local_name' => 'Mascarilla hidratante en velo – äKwä', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'transfer-factor-glucoach', 'local_name' => '4Life GL-Coach', 'match_confidence' => 'exact'],
            ['country_id' => 37, 'product_slug' => 'tea4life', 'local_name' => 'Tea4Life', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'tf-boost-sachets', 'local_name' => 'TF - Boost', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'riovida-liquid', 'local_name' => 'RioVida Liquido', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => '4Life Plus', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => 'ECM', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix - Berry', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'riovida-stix', 'local_name' => 'RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'transfer-factor-collagen', 'local_name' => '4Life Collagen', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Pre/O Biotics', 'match_confidence' => 'exact'],
            ['country_id' => 10, 'product_slug' => 'pro-tf-protein', 'local_name' => 'Pro-TF Chocolate', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-agepro', 'local_name' => 'AG-Pro Cápsula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'tf-boost-sachets', 'local_name' => 'TF-Boost Polvo Oral', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'riovida-liquid', 'local_name' => '4Life Transfer Factor Riovida Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => '4Life Transfer Factor Plus Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => '4Life Transfer Factor Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-recall', 'local_name' => 'Transfer Factor ReCall', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => '4Life Transfer Factor Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix sabor Berry Polvo Oral', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => '4Life Transfer Factor Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-cardio', 'local_name' => '4LIFE TRANSFER FACTOR BCV Tri-Factor Fórmula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-glucoach', 'local_name' => '4Life Transfer Factor GluCoach', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'riovida-stix', 'local_name' => '4Life Transfer Factor RioVida Stix Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'nanofactor-glutamine-prime', 'local_name' => 'Nano Factor Glutamine Prime', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'riovida-burst', 'local_name' => '4Life Transfer Factor RioVida Burst Tri-Factor Formula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-collagen', 'local_name' => 'Collagen Polvo para Suspensión Oral', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Pre/O Biotics', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-kbu', 'local_name' => 'KBU Cápsula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'nutrastart-blue-vanilla', 'local_name' => 'NutraShake Polvo Oral', 'match_confidence' => 'similar'],
            ['country_id' => 42, 'product_slug' => 'fibre-system-plus', 'local_name' => 'Fibre System Plus', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-vista', 'local_name' => '4Life Transfer Factor Vistari (cápsula)', 'match_confidence' => 'similar'],
            ['country_id' => 42, 'product_slug' => 'pro-tf-protein', 'local_name' => 'PRO-TF (Sabor chocolate)', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'transfer-factor-chewable', 'local_name' => 'Chewable Tri-Factor Formula Tableta Masticable', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'essential-fatty-acid-complex', 'local_name' => 'Essential Fatty Acid Complex', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'digestive-enzymes', 'local_name' => 'Enzimas Digestivas Cápsula', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'cal-mag-complex', 'local_name' => 'CM Complex', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'enummi-toothpaste', 'local_name' => 'enummi Toothpaste (crema dental)', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'akwa-moisturizing-cream', 'local_name' => 'aKwa Moisture Cream', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'akwa-oil-to-foam-cleanser', 'local_name' => 'aKwa Oil-To-Foam Cleanser', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'akwa-vitamin-serum', 'local_name' => 'aKwa Vitamin Serum', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'akwa-revitalizing-eye-cream', 'local_name' => 'aKwa Refining Eye Cream', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'akwa-four-in-one-toner', 'local_name' => 'aKwa Four-Way Toner', 'match_confidence' => 'exact'],
            ['country_id' => 42, 'product_slug' => 'akwa-sheet-mask', 'local_name' => 'aKwa Hydrating Sheet Mask', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => 'Transfer Factor Plus', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => 'Transfer Factor Tri-Factor', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-cardio', 'local_name' => 'BCV', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-renuvo', 'local_name' => 'Renuvo', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-recall', 'local_name' => 'Transfer Factor Recall', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => 'Transfer Factor Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'riovida-burst', 'local_name' => 'RioVida Burst', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-glucoach', 'local_name' => 'Transfer Factor GluCoach', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'essential-fatty-acid-complex', 'local_name' => 'BioEFA', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'energy-go-stix', 'local_name' => 'Energy Go Stix - Berry', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'pre-o-biotics', 'local_name' => 'Pre/Obiotics', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-kbu', 'local_name' => 'KBU', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-collagen', 'local_name' => '4Life Transfer Factor Colágeno', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'tf-boost-sachets', 'local_name' => '4Life TF-Boost', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'nutrastart-blue-vanilla', 'local_name' => 'NutraStart NF', 'match_confidence' => 'similar'],
            ['country_id' => 18, 'product_slug' => 'nanofactor-glutamine-prime', 'local_name' => 'TARGETED TRANSFER FACTOR GLUTAMINE PRIME', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'riovida-stix', 'local_name' => 'RioVida Stix', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-vista', 'local_name' => '4LIFE TRANSFER FACTOR VISTARI', 'match_confidence' => 'similar'],
            ['country_id' => 18, 'product_slug' => 'fibre-system-plus', 'local_name' => 'Fiber System Plus', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-agepro', 'local_name' => 'AG-Pro', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'aloe-vera-stix', 'local_name' => 'Aloe Vera Stix Tropical', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'pro-tf-protein', 'local_name' => 'PRO-TF Proteína', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'enummi-body-lotion', 'local_name' => 'Intensive Body Lotion', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'enummi-toothpaste', 'local_name' => 'enummi Toothpaste', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'akwa-moisturizing-cream', 'local_name' => 'akwa Crema Humectante', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'akwa-oil-to-foam-cleanser', 'local_name' => 'akwa Limpiador', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'akwa-revitalizing-eye-cream', 'local_name' => 'akwa Crema de Ojos', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'akwa-vitamin-serum', 'local_name' => 'akwa Suero', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'akwa-four-in-one-toner', 'local_name' => 'akwa Tonico', 'match_confidence' => 'exact'],
            ['country_id' => 18, 'product_slug' => 'transfer-factor-malepro', 'local_name' => 'Transfer-Factor MalePro', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'tf-boost-sachets', 'local_name' => '4Life Transfer Factor Boost', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'transfer-factor-plus-tri-factor', 'local_name' => 'Transfer Factor Plus', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'riovida-stix', 'local_name' => 'RioVida Stix 15 packets/carton', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'transfer-factor-belle-vie', 'local_name' => 'Belle Vie', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'super-detox', 'local_name' => 'Super Detox', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'transfer-factor-recall', 'local_name' => 'Transfer Factor Recall', 'match_confidence' => 'exact'],
            ['country_id' => 7, 'product_slug' => 'transfer-factor-tri-factor', 'local_name' => 'Transfer Factor Tri-Factor', 'match_confidence' => 'exact'],
        ];

        foreach ($aliases as $alias) {
            $product = FlProductReference::where('slug', $alias['product_slug'])->first();
            if (!$product) continue;

            DB::table('fl_product_aliases')->insert([
                'reference_id' => $product->id,
                'country_id' => $alias['country_id'],
                'product_id' => null,
                'local_name' => $alias['local_name'],
                'match_confidence' => $alias['match_confidence'],
                'composition_notes' => null,
                'is_confirmed' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}