<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FlProductsChileSeeder extends Seeder
{
    public function run(): void
    {
        $countryId = 10;

        $rows = [
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310256795',
                'name'                => 'Esencia Joven',
                'slug'                => Str::slug('Esencia Joven'),
                'url'                 => 'https://chile.4life.com/corp/product/esencia-joven/4514',
                'image_url'           => 'https://media2.4life.com/products/Chile_collagen_new_image.webp?width=200&mode=crop&quality=80',
                'description'         => 'ESENCIA JOVEN 20%',
                'price'               => 23020,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => 'Flash Sale',
                'category'            => 'skin',
                'sort_order'          => 1,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310256794',
                'name'                => 'Plus Total',
                'slug'                => Str::slug('Plus Total'),
                'url'                 => 'https://chile.4life.com/corp/product/plus-total/4530',
                'image_url'           => 'https://media2.4life.com/products/Chile_plus_imagen_nuevo.webp?width=200&mode=crop&quality=80',
                'description'         => 'Oportunidad UNICA',
                'price'               => 36640,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => 'Flash Sale',
                'category'            => 'general',
                'sort_order'          => 2,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310293580',
                'name'                => 'Pack Constructor',
                'slug'                => Str::slug('Pack Constructor'),
                'url'                 => 'https://chile.4life.com/corp/product/pack-constructor---chile/4221',
                'image_url'           => 'https://media2.4life.com/products/Chile_abril_pack_constructor.jpg?width=200&mode=crop&quality=80',
                'description'         => '¡Impulsa tu bienestar con 4Life!',
                'price'               => 144220,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'general',
                'sort_order'          => 3,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 4,
                'external_id'         => '310228136',
                'name'                => 'TF - Boost',
                'slug'                => Str::slug('TF - Boost'),
                'url'                 => 'https://chile.4life.com/corp/product/tf---boost---chile/3781',
                'image_url'           => 'https://media2.4life.com/products/chile_tf_boost_uno.jpg?width=200&mode=crop&quality=80',
                'description'         => '¡El único producto de 4Life que contiene 1.000 mg de vitamina C!',
                'price'               => 18800,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'sachets',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'immune',
                'sort_order'          => 4,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310256047',
                'name'                => 'Pack Energy +',
                'slug'                => Str::slug('Pack Energy +'),
                'url'                 => 'https://chile.4life.com/corp/product/pack-energy/3561',
                'image_url'           => 'https://media2.4life.com/products/Chile_pack_energy_plus.jpg?width=200&mode=crop&quality=80',
                'description'         => '¡Llénate de energía con este súper pack!',
                'price'               => 156141,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'energy',
                'sort_order'          => 5,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310293632',
                'name'                => 'Pack Dosis Diaria',
                'slug'                => Str::slug('Pack Dosis Diaria'),
                'url'                 => 'https://chile.4life.com/corp/product/pack-dosis-diaria---ch/4502',
                'image_url'           => 'https://media2.4life.com/products/Chile_feb_dosis_diraria_pack.webp?width=200&mode=crop&quality=80',
                'description'         => '¡Impulsa tu bienestar con 4Life!',
                'price'               => 145440,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'general',
                'sort_order'          => 6,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 75,
                'external_id'         => '310224141',
                'name'                => 'RioVida Liquido',
                'slug'                => Str::slug('RioVida Liquido'),
                'url'                 => 'https://chile.4life.com/corp/product/transfer-factor-riovida/93',
                'image_url'           => 'https://media2.4life.com/products/Chile_riovida_single_bottle.webp?width=200&mode=crop&quality=80',
                'description'         => '¡Impulsa tu bienestar con 4Life!',
                'price'               => 37550,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'liquid',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'immune',
                'sort_order'          => 7,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310256826',
                'name'                => 'Pack Equilibrio Digestivo',
                'slug'                => Str::slug('Pack Equilibrio Digestivo'),
                'url'                 => 'https://chile.4life.com/corp/product/pack-equilibrio-digestivo/4529',
                'image_url'           => 'https://media2.4life.com/products/Chile_pack_equilibrio_digestivo.webp?width=200&mode=crop&quality=80',
                'description'         => 'Oportunidad UNICA',
                'price'               => 163510,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'digestive',
                'sort_order'          => 8,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310293630',
                'name'                => 'Inicio Acelerado Completo',
                'slug'                => Str::slug('Inicio Acelerado Completo'),
                'url'                 => 'https://chile.4life.com/corp/product/inicio-acelerado-completo---chile/4500',
                'image_url'           => 'https://media2.4life.com/products/chile_ia_completo.webp?width=200&mode=crop&quality=80',
                'description'         => '¡Impulsa tu bienestar con 4Life!',
                'price'               => 433430,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'general',
                'sort_order'          => 9,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '320293631',
                'name'                => 'Inicio Acelerado Fundamental',
                'slug'                => Str::slug('Inicio Acelerado Fundamental'),
                'url'                 => 'https://chile.4life.com/corp/product/inicio-acelerado-fundamental---chile/4501',
                'image_url'           => 'https://media2.4life.com/products/chile_ia_fundamental.webp?width=200&mode=crop&quality=80',
                'description'         => '¡Impulsa tu bienestar con 4Life!',
                'price'               => 371160,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'general',
                'sort_order'          => 10,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 1,
                'external_id'         => '310224075',
                'name'                => '4Life Plus ',
                'slug'                => Str::slug('4Life Plus '),
                'url'                 => 'https://chile.4life.com/corp/product/4life-plus/1117',
                'image_url'           => 'https://media2.4life.com/products/chile_new_plus.jpg?width=200&mode=crop&quality=80',
                'description'         => 'Nuestro princial producto, que contiene la Tri - Fórmula e  ingredientes conocidos por su beneficio de equilibrar el sistema inmunológico.',
                'price'               => 47460,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'capsules',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'immune',
                'sort_order'          => 11,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => null,
                'external_id'         => '310254625',
                'name'                => 'Pack Super Plus',
                'slug'                => Str::slug('Pack Super Plus'),
                'url'                 => 'https://chile.4life.com/corp/product/pack-super-plus/1897',
                'image_url'           => 'https://media2.4life.com/products/Chile_pack_super_plus.jpg?width=200&mode=crop&quality=80',
                'description'         => 'Pack Super Plus',
                'price'               => 137415,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'other',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => true,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'immune',
                'sort_order'          => 12,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 2,
                'external_id'         => '310224070',
                'name'                => 'ECM',
                'slug'                => Str::slug('ECM'),
                'url'                 => 'https://chile.4life.com/corp/product/transfer-factor-tri-factor/95',
                'image_url'           => 'https://media2.4life.com/products/chile_ecm_nuevo.jpg?width=200&mode=crop&quality=80',
                'description'         => 'Un clásidco de 4Life que contiene la Tri - Factor Fórmula.',
                'price'               => 34047,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'capsules',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'immune',
                'sort_order'          => 13,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 47,
                'external_id'         => '310227563',
                'name'                => 'Energy Go Stix - Berry',
                'slug'                => Str::slug('Energy Go Stix - Berry'),
                'url'                 => 'https://chile.4life.com/corp/product/energy-go-stix---berry/119',
                'image_url'           => 'https://media2.4life.com/products/Chile_energy_go_stix_new_image.jpg?width=200&mode=crop&quality=80',
                'description'         => 'La Energía perfecta y natural en tu rutina diaria.',
                'price'               => 42642,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'sachets',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'energy',
                'sort_order'          => 14,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 6,
                'external_id'         => '310224113',
                'name'                => 'RioVida Stix',
                'slug'                => Str::slug('RioVida Stix'),
                'url'                 => 'https://chile.4life.com/corp/product/transfer-factor-riovida-stix/102',
                'image_url'           => 'https://media2.4life.com/products/Chile_riovida_stix_nuevo.jpg?width=200&mode=crop&quality=80',
                'description'         => 'Exquisita bebida para preparar, con ingredientes conocidos por su alto poder antioxidante.',
                'price'               => 25336,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'sachets',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'immune',
                'sort_order'          => 15,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 25,
                'external_id'         => '310225404',
                'name'                => '4Life Collagen',
                'slug'                => Str::slug('4Life Collagen'),
                'url'                 => 'https://chile.4life.com/corp/product/4-life-collagen/2170',
                'image_url'           => 'https://media2.4life.com/products/Chile_collagen_new_image.jpg?width=200&mode=crop&quality=80',
                'description'         => 'Colágeno Hidrolizado + 4Life Tri-Fórmula. Aporta colágeno para mantener el nivel necesario para el bienestar de tu piel, articulaciones, etc.',
                'price'               => 29832,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'sachets',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'skin',
                'sort_order'          => 16,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 10,
                'external_id'         => '310223020',
                'name'                => 'Pre/O Biotics',
                'slug'                => Str::slug('Pre/O Biotics'),
                'url'                 => 'https://chile.4life.com/corp/product/preo-biotics-chile/1842',
                'image_url'           => 'https://media2.4life.com/products/Chile_preo_nuevo.jpg?width=200&mode=crop&quality=80',
                'description'         => '¿Hinchazón?  Preocupate de tu bienestar  intestinal con Pre/O Biotics.',
                'price'               => 37668,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'sachets',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'digestive',
                'sort_order'          => 17,
            ],
            [
                'country_id'          => 10,
                'reference_id'        => 8,
                'external_id'         => '310227577',
                'name'                => 'Pro-TF Chocolate',
                'slug'                => Str::slug('Pro-TF Chocolate'),
                'url'                 => 'https://chile.4life.com/corp/product/pro-tfr-chocolate/662',
                'image_url'           => 'https://media2.4life.com/products/Chile_protf_nueva.jpg?width=200&mode=crop&quality=80',
                'description'         => 'La proteína perfecta en tu rutina diaria.',
                'price'               => 51054,
                'price_wholesale'     => null,
                'price_loyalty'       => null,
                'currency_code'       => 'CLP',
                'format'              => 'powder',
                'units_per_container' => null,
                'serving_size'        => null,
                'is_pack'             => false,
                'is_available'        => true,
                'is_on_promotion'     => true,
                'promotion_details'   => null,
                'category'            => 'general',
                'sort_order'          => 18,
            ],
        ];

        // Normaliza timestamps si tu tabla los requiere
        $now = now();
        $rows = array_map(function ($row) use ($now) {
            $row['created_at'] = $row['created_at'] ?? $now;
            $row['updated_at'] = $now;
            return $row;
        }, $rows);

        DB::table('fl_products')->upsert(
            $rows,
            ['country_id', 'external_id'],
            [
                'reference_id',
                'name',
                'slug',
                'url',
                'image_url',
                'description',
                'price',
                'price_wholesale',
                'price_loyalty',
                'currency_code',
                'format',
                'units_per_container',
                'serving_size',
                'is_pack',
                'is_available',
                'is_on_promotion',
                'promotion_details',
                'category',
                'sort_order',
                'updated_at',
            ]
        );
    }
}
